-- Generated by scripts/generate-company-web-enrichment-sql.mjs
-- Generated at: 2026-06-27T10:57:10.166Z
-- OpenDART matched companies: 82 / 85
-- Official career links detected: 27

begin;

delete from public.job_postings
where source_id in (
  select id from public.company_sources
  where source_type in ('official_homepage_career_link')
);

update public.company_profiles profile
set careers_page_url = null,
    updated_at = now()
where exists (
  select 1 from public.company_sources source
  where source.company_id = profile.company_id
    and source.source_type = 'official_homepage_career_link'
    and source.source_url = profile.careers_page_url
);

update public.companies company
set careers_page_url = null
where exists (
  select 1 from public.company_sources source
  where source.company_id = company.id
    and source.source_type = 'official_homepage_career_link'
    and source.source_url = company.careers_page_url
);

delete from public.company_sources
where source_type in ('opendart_company_profile', 'official_homepage_career_link');


with rows(
  company_id, verified_name, homepage_url, careers_page_url, address, stock_code, dart_corp_code,
  ceo_name, phone, ir_url, industry_code, founded_date, data_quality_score
) as (
  values
(1, '주식회사강남', 'https://www.knsol.co.kr', null, '경상남도 창원시 의창구 대산면 주남로400번길 37 (제동리)', null, '00671899', '김병준', '055-250-5433', null, '291', '20041101', 74),
(2, '고려화공(주)', null, null, '부산광역시 서구 충무동1가 39-5 우양빌딩 8층', null, '00227634', '조효식', '051-256-1771', null, '20494', '19890421', 62),
(3, '(주)광림', 'https://www.kanglim.com', 'https://www.kanglim.com/company/recruit', '충청북도 청원군  현도면 청남로 484 (주)광림', '014200', '00103635', '황태영', '043-260-9111', 'https://kanglim.com/', '301', '19800313', 82),
(4, '기아(주)', 'https://www.kia.co.kr', null, '서울특별시 서초구 헌릉로 12 기아자동차', '000270', '00106641', '송호성', '02-3464-1114', null, '30121', '19441210', 74),
(5, '다산기공(주)', null, null, '전라북도 완주군 봉동읍 테크노밸리2로 17 (장구리)', null, '00809438', '김병군', '063-261-0411', null, '292', '20050608', 62),
(6, '주식회사 다윈프릭션', 'https://www.dawinf.co.kr', null, '인천광역시 남동구 남동동로197번길 20', null, '00863436', '조정환', '032-821-4621', null, '31322', '20030219', 74),
(7, '단암시스템즈주식회사', null, null, '경기도 안양시 동안구 동편로 79-26 단암시스템즈주식회사', null, '00459279', '이성혁', '031-420-4300', null, '2642', '20011001', 62),
(8, '주식회사 대명', null, null, '경상남도 양산시 유산동 217', null, '00172361', '이 한 우', '055-382-0091', null, '15110', '19851102', 62),
(9, '(주)대신금속', null, null, '부산광역시 사상구 감전동 956-8', null, '00828239', '김기철', '051-323-9992', null, '33', '19960901', 62),
(10, '대양전기공업(주)', 'https://daeyang.co.kr', null, '부산광역시 사하구 장평로 245', '108380', '00111193', '서영우', '051-200-5331', null, '31114', '19880701', 74),
(11, '(주)대영에스텍', null, null, '대전광역시 유성구 국제과학3로 23 (신동)', null, '00867308', '강원구', '042-864-2500', null, '26429', '19990106', 62),
(12, '(주)대한항공', 'https://www.koreanair.com', 'https://www.koreanair.com/recruit', '서울특별시 강서구 하늘길 260', '003490', '00113526', '조원태, 우기홍', '02-2656-7114', null, '511', '19620619', 82),
(13, '덕산넵코어스주식회사', null, null, '대전광역시 유성구 테크노2로 66-6 (관평동)', null, '00960623', '황태호', '042-363-9000', null, '2629', '20121228', 62),
(14, '(주)데크카본', 'https://www.dacc21.co.kr', null, '전라북도 전주시 덕진구 운암로 30 (팔복동2가)', null, '01040555', '김광수, 강희순', '063-715-2501', null, '31322', '20140429', 74),
(15, '동양정공(주)', null, null, '경상남도 통영시 광도면 황리 안정국가산업단지 3-6-1', null, '00455343', '이낙영', '055-649-6801', null, '31114', '20011109', 62),
(16, '주식회사 동인광학', 'https://www.donginoptical.com', null, '경기도 부천시 석천로380번길 1 (삼정동, (주)동인광학)', null, '00926212', '정  인', '032-328-9935', null, '27', '20080909', 74),
(17, '두산에너빌리티(주)', 'https://www.doosanenerbility.com/kr', 'https://www.doosanenerbility.com/kr/employment/talent_02', '경상남도 창원시 성산구  두산볼보로 22 두산중공업 주식회사', '034020', '00159616', '박지원, 정연인, 박상현', '055-278-6114', 'https://www.doosanenerbility.com/kr/investment/ir_data', '29119', '19620920', 82),
(18, '두원중공업 주식회사', 'https://www.doowonhi.com', 'https://www.saramin.co.kr/zf_user/company-info/view-inner-recruit?csn=RHZsVTQ4cGZPWjVuZXJoOEptS095dz09', '경상남도 사천시 축동면 구해창길 20-7', null, '00119724', '김태훈', '055)851-2121', null, '30', '19790301', 82),
(19, '(주)씨솔루션', null, null, '서울특별시 강남구 논현동 97-7 청호빌딩 4층', null, '00361743', '정형동', '517-4777', null, '25991', '19990812', 62),
(20, '(주)  미래  엠  텍', 'https://www.miraemtech.com', null, '대구광역시 달서구 신당동 1187-9', null, '00879729', '배석암', '053-585-2800', null, '24329', '20070817', 74),
(21, '(주) 비츠로밀텍', 'https://vitzromiltech.com', null, '충청남도 천안시 동남구 풍세면 풍세산단로 58 (용정리) 비츠로밀텍', null, '01263077', '변영철', '02-2024-3122', null, '28201', '19920123', 74),
(22, '(주)빅텍', 'https://www.victek.co.kr', null, '인천광역시 연수구 연구단지로55번길 25 -', '065450', '00385363', '임만규', '032-813-7301', null, '27211', '19960109', 74),
(23, '(주)삼양정밀화학', 'https://syfc.co.kr', null, '경상남도 양산시 회현1길 125 (교동)', null, '01834079', '오광세', '0234885422', null, '20499', '20131216', 74),
(24, '주식회사 삼양컴텍', 'https://samyangct.com', 'https://samyangct.com/recruit', '서울특별시 서초구 반포대로27길 16, 8층(서초동, 파크빌딩)', '484590', '00141583', '김종일', '02-3488-5552', null, '25200', '19621222', 82),
(25, '삼양화학공업(주)', null, null, '서울특별시 서초구 반포대로27길 16 (서초동) 파크빌딩 8층 삼양화학공업', null, '00127088', '이용대', '02-3488-5413', null, '2049', '19880104', 62),
(26, '삼영이엔씨(주)', 'https://www.samyungenc.com', null, '부산광역시 영도구  상리로 69', '065570', '00288343', '김중철', '(051)601-6666', null, '26429', '19950206', 74),
(27, '주식회사 삼정터빈', 'https://www.turbine.co.kr', null, '경상남도 김해시 진례면 고모로180번길 116 (송현리)', null, '00221560', '정진욱', '055-345-6971', null, '30', '19740226', 74),
(28, '주식회사티비엠', 'https://www.aerospacetbm.com', null, '경상남도 김해시 진례면 고모로180번길 116', null, '02004815', '정재우', '0553423533', null, '24329', '20200713', 74),
(29, '(주)삼주기업', 'https://www.samjurubber.com', null, '대구광역시 달서구 달서대로64길 29 (대천동)', null, '01138832', '박진우', '053-581-5192', null, '2219', '19970321', 74),
(30, '성진테크윈', 'https://www.switch-vr.com', null, '대전광역시 동구 계족로 45-10 (인동) 성진테크윈', null, '01251027', '이계광', '042-271-1177', null, '26299', '20010901', 74),
(31, '주식회사 세아항공방산소재', null, null, '경상남도 창원시 성산구 정동로 48 (성주동, (주)세아항공방산소재)', null, '00456698', '성창모', '055-269-9526', null, '24212', '20011206', 62),
(32, '(주)스페코', 'https://www.speco.co.kr', null, '서울특별시 강남구 학동로 171 삼익빌딩 7층', '013810', '00136165', '이열', '02-3498-3243', null, '29229', '19790207', 74),
(33, '(주)시공사', 'https://sigongsa.koreasme.com', null, '경상남도 김해시 주촌면 내삼리 1195-8', null, '00564836', '윤중', '055-338-0077', null, '30', '19951001', 74),
(34, '신정개발특장차(주)', 'https://www.shinjeong.co.kr', null, '울산광역시 울주군 언양읍 곰재길 169 (반천리, (주)신정개발)', null, '00914156', '김종순', '052-263-9647', null, '3020', '20111020', 74),
(35, '주식회사쎄트렉아이', 'https://www.satreci.com', 'https://satreci.recruiter.co.kr/career/home', '대전광역시 유성구 엑스포로 441 (문지동)', '099320', '00449254', '김이을', '042-365-7500', 'www.satreci.com', '3131', '19991229', 82),
(36, '주식회사 씨앤지', 'https://www.ecng.co.kr', 'https://www.ecng.co.kr/recruit', '전라남도 순천시 서면 구상리 152-4', null, '00677662', '강규태', '061-725-8712', null, '19229', '19981001', 82),
(37, '아이쓰리시스템(주)', 'https://www.i3system.com', 'http://i3system.com/%ec%9d%b8%ec%9e%ac%ec%b1%84%ec%9a%a9/%ec%b1%84%ec%9a%a9%ec%a0%95%eb%b3%b4', '대전광역시 유성구 테크노5로 69', '214430', '00612489', '정한', '070-4162-0781', null, '2629', '19980711', 82),
(38, '아이펙스 주식회사', null, null, '서울특별시 금천구 가산디지털1로 189 (가산동, (주)LG가산디지털센터) 11층', null, '01004298', '패트릭 롤프 요한슨', '01077641986', null, '46522', '20131101', 62),
(39, '주식회사 에비오시스 테크놀러지스', 'https://www.aviosystech.com', 'https://www.aviosystech.com/page/sub04-1.php', '경기도 성남시 분당구 판교로 723 (야탑동) 분당테크노파크 B동 802호', null, '01546305', '김기성', '070-4863-8957', null, '31322', '20131206', 82),
(40, '(주)에이치케이', 'https://www.hk-global.com', 'https://www.hk-global.com/ko/recruit/want.html', '경기도 화성시 양감면 사릅재길 117', '044780', '00235183', '계명재', '031-350-2800', null, '29221', '19900530', 82),
(41, '연합정밀주식회사', 'https://www.yeonhab.co.kr', null, '충청남도 천안시 동남구 목천읍 학수소사길 219-27 (소사리, 연합정밀기술연구소)', null, '00140371', '김인술', '041-566-5992', null, '28123', '19800602', 74),
(42, '주식회사우경광학', 'https://www.wkoptics.com', null, '경기도 안산시 단원구 해봉로330번길 8 (신길동, 정우벤처타운1) 301호', null, '01564310', '류재복', '031-495-5319', null, '27301', '20120720', 74),
(43, '주식회사 우리별', 'https://www.wooribyul.co.kr', null, '경기도 김포시 양촌면 학운리 2962', null, '00767682', '이정석', '031-980-7500', null, '264', '20080501', 74),
(44, '주식회사 유아이헬리콥터', null, null, '서울특별시 마포구 독막로 311 (염리동, 재화스퀘어) 16층', null, '00619233', '전해종', '02-3470-8319', null, '3131', '19861204', 62),
(45, '(주)유텍', 'https://www.utech.co.kr', null, '대전광역시 유성구 반석로 10 (반석동, 반석역프라자), 8층 801호', null, '01552689', '황인협', '070-4496-1000', null, '27309', '19990513', 74),
(46, '주식회사 은성사', 'https://www.silstar.co.kr', 'https://www.silstar.co.kr/recruit', '부산광역시 사하구 다산로175번길 20 (다대동)', null, '00145349', '박보국', '051-601-9122', null, '33303', '19731107', 82),
(47, '큐리옥스바이오시스템즈(주)', 'https://curiox.co.kr', 'https://curiox.co.kr/sub/careers/recruitment.asp', '서울특별시 금천구 디지털로9길 41 2층 202호, 204호 ~ 213호 (가산동, 삼성아이티해링턴타워) &nbsp', '445680', '01498974', '김남용', '02-2039-7160', null, '271', '20180907', 82),
(48, '이화전기공업(주)', 'https://www.eti21.com', null, '서울특별시 강남구  논현로 746 석호빌딩', '024810', '00145738', '백성현', '02-3440-0276', null, '2811', '19650603', 74),
(49, '인소팩주식회사', 'https://www.insopack.co.kr', null, '대전광역시 유성구 가정로 218 (가정동, 한국전자통신연구원)융합기술연구생산센터 708호', null, '00959292', '손동철', '1544-9013', null, '26429', '20000428', 74),
(50, '주식회사 스페이스프로', 'https://www.spacepro.co.kr', 'https://www.spacepro.co.kr/bbs/board.php?bo_table=careers', '경상남도 밀양시 부북면 춘화로 85 스페이스프로', null, '00160597', '최용균', '055-355-0081', null, '23121', '19770701', 82),
(51, '(주)인피니티', 'https://www.dktec.co.kr', null, '인천광역시 계양구 아나지로 412 (작전동)', null, '00626109', '유승찬', '032-540-8773', null, '30', '19940801', 74),
(52, '주식회사 진영정기', 'https://www.kojin.co.kr', null, '경기도 화성시 장안면 장안로 566-21', null, '00150581', '최재옥', '031-366-0093', 'www.kojin.co.kr', '29293', '19680118', 74),
(53, '(주)캐스', 'https://www.kaes.biz', 'https://www.kaes.biz/recruit', '충청남도 아산시 둔포면 아산밸리로 312 (석곡리, (주)케스)', null, '00652946', '이은광', '041-420-9600', null, '31322', '19990812', 82),
(54, '(주)코리아 디펜스 인더스트리', null, null, '세종특별자치시 세종로 1229 (고운동, 스타플레이스) 707호', null, '01511567', '정정모', '044-850-4041', null, '25200', '20201102', 62),
(55, '(주)코오롱', 'https://www.kolon.com', null, '경기 과천시 별양동 1-23 코오롱타워', '002020', '00152862', '안병덕, 이규호', '02-3677-3114', null, '64992', '19570412', 74),
(56, '티에스주식회사', 'https://www.tsglobal.co.kr', null, '강원도 원주시 소초면 현촌길 108', null, '01154575', '김수훈', '033-748-5133', null, '30121', '20040401', 74),
(57, '퍼스텍(주)', 'https://www.firsteccom.co.kr', 'https://www.firsteccom.co.kr/recruit/recruit_01', '경상남도 창원시 성산구  남면로 485 퍼스텍(주)', '010820', '00148522', '손경석', '031-627-4534', null, '252', '19750925', 82),
(58, '평화산업(주)', 'https://www.ph.co.kr', null, '대구광역시 달성군 논공읍 논공로 597', '090080', '00573579', '황순용, 김주영', '053-610-7027', null, '303', '20060502', 74),
(59, '(주)풍산', 'https://www.poongsan.co.kr', 'https://www.poongsan.co.kr/recruit/disclosure/information', '경기도 평택시  포승읍 평택항로156번길 134 (주)풍산', '103140', '00684714', '류진, 박우동', '02-3406-5846', null, '242', '20080704', 82),
(60, '(주)풍산에프앤에스', 'https://www.poongsanfns.co.kr', 'https://www.poongsanfns.co.kr/career', '충청남도 논산시 은진면 득안대로 893 (토양리)', null, '00165219', '류상우', '041-740-5513', null, '27', '19730123', 82),
(61, '한국특수전지(주)', 'https://www.ksbatteries.com', null, '경상남도 창원시 성산구 웅남로 780 한국특수전지(주)', null, '00249016', '추은명', '055-239-5800', null, '2811', '19970320', 74),
(62, '한국항공우주산업(주)', 'https://www.koreaaero.com', 'https://www.koreaaero.com/recruit', '경상남도 사천시  사남면 공단1로 78 한국항공우주산업', '047810', '00309503', '김종출', '055-851-1000', null, '31311', '19991001', 82),
(63, '한일단조공업(주)', 'https://www.hifg.co.kr', null, '충청북도 진천군 덕산면 습지길 87 한일단조공업주식회사', '024740', '00162832', '박정영', '043-536-5181', null, '303', '19660516', 74),
(64, '주식회사 한컴라이프케어', 'https://www.hancomlifecare.com', null, '경기도 용인시 처인구 양지면 중부대로1960번길 53', '372910', '00534598', '김선영', '031-5183-9021', 'hancomlifecare.irpage.co.kr/#/main', '27199', '19711221', 74),
(65, '한화오션(주)', 'https://www.hanwhaocean.com/pub/main/index.do', 'https://www.hanwhaocean.com/careers/ri', '경상남도 거제시 거제대로 3370 (아주동)', '042660', '00111704', '김희철', '055-735-2114', 'https://www.hanwhaocean.com/', '3111', '20001023', 82),
(66, '한화시스템(주)', 'https://hanwhasystems.com', null, '경상북도 구미시 산호대로 264-60 -', '272210', '00339391', '손재일', '02-729-4605', 'www.hanwhasystems.com', '26299', '20000111', 74),
(67, '한화에어로스페이스(주)', 'https://www.hanwhaaerospace.com', 'https://www.hanwhaaerospace.com/kor/careers/recruit.do', '경상남도 창원시 성산구  창원대로 1204', '012450', '00126566', '김동관, 손재일', '055-260-2114', null, '31321', '19770801', 82),
(68, '현대로템(주)', 'https://www.hyundai-rotem.co.kr', null, '경상남도 창원시 의창구  창원대로 488', '064350', '00302926', '이용배', '055-273-1341', null, '31910', '19990701', 74),
(69, '현대위아(주)', 'https://www.hyundai-wia.com', 'https://www.hyundai-wia.com/recruit', '경상남도 창원시 성산구  정동로 153', '011210', '00106623', '권오성', '055-280-9114', null, '303', '19760329', 82),
(70, '(주)현대제이콤', null, null, '경기도 성남시 중원구 사기막골로105번길 27 (상대원동)중앙인더스피아 3차 5층 501호', null, '00409016', '박병준', '031-639-2700', null, '26410', '20010510', 62),
(71, '현대트랜시스주식회사', 'https://www.hyundai-transys.com', 'https://www.hyundai-transys.com/ko/careers/jobs.do', '충청남도 서산시 성연면 신당1로 105 (갈현리, 현대트랜시스(주))', null, '00302634', '백철승', '031-369-9993', null, '30', '19991228', 82),
(73, '효성중공업(주)', 'https://www.hyosungheavyindustries.com', 'https://www.hyosungheavyindustries.com/kr/company/recruitment/ideal-talent', '서울특별시 마포구 마포대로 119 효성빌딩', '298040', '01316245', '우태희', '02-707-7000', null, '281', '20180604', 82),
(74, '(주)휴니드테크놀러지스', 'https://www.huneed.com', 'https://www.huneed.com/%EC%B1%84%EC%9A%A9%EA%B3%B5%EA%B3%A0', '인천광역시 연수구  벤처로 87', '005870', '00111421', '이철승', '032-457-6000', null, '2642', '19681211', 82),
(75, '에이치디현대인프라코어(주)', 'https://www.hd-infracore.com', null, '인천광역시 동구  인중로 489(화수동)', '042670', '00344287', '조영철, 오승현', '032-211-1114', null, '29241', '20001023', 74),
(76, '에이치디현대중공업모스 주식회사', null, null, '울산광역시 동구 방어진순환도로 1000 (전하동, 현대중공업(주))', null, '01169346', '김병조', '052-203-3004', null, '74100', '20160725', 62),
(77, '(주)에이치제이', 'https://www.hjlite.com', 'https://www.hjlite.com/recruit', '경기도 화성시 향남읍 발안공단로4길 30', null, '00865115', '윤세원', '031-353-3030', null, '13994', '19960201', 82),
(78, '주식회사 엘아이지', 'https://www.ligcorp.com', 'https://www.ligcorp.com/recruit', '서울특별시 강남구 역삼1동 푸르덴셜타워 10층', null, '00576619', '오춘석', '02-6900-1935', null, '64992', '20000620', 82),
(79, '(주)엠트론', 'https://www.mtron.net', null, '경기도 성남시 중원구 상대원동 307-2 선텍시티 II', null, '00597047', '전형관', '0317374820', null, '263', '20051011', 74),
(82, '케이오 주식회사', null, null, '서울특별시 강서구 마곡서로 101 (마곡동, 동익드미라벨복합빌딩) 826호', null, '01096068', '전인배', '02-2601-9833', null, '52939', '20150303', 62),
(83, '주식회사 에스앤티', null, null, '대전광역시 유성구 용계동 도안택지개발사업지구상 9-2블럭', null, '00943918', '이철진', '042-542-6200', null, '6822', '20110511', 62),
(84, '주식회사 에스앤티', null, null, '대전광역시 유성구 용계동 도안택지개발사업지구상 9-2블럭', null, '00943918', '이철진', '042-542-6200', null, '6822', '20110511', 62),
(85, 'STX엔진(주)', 'https://www.stxengine.co.kr', 'https://www.stxengine.co.kr/kor/html/recruit/talent.aspx', '경상남도 창원시 성산구  공단로474번길 36', '077970', '00480455', '이상수', '-', null, '29111', '20040401', 82)
)
insert into public.company_profiles (
  company_id, verified_name, homepage_url, careers_page_url, address, stock_code, dart_corp_code,
  summary, data_quality_score, updated_at
)
select
  company_id,
  verified_name,
  homepage_url,
  careers_page_url,
  address,
  stock_code,
  dart_corp_code,
  concat_ws(' · ', nullif(ceo_name, ''), nullif(phone, ''), nullif(industry_code, ''), nullif(founded_date, '')),
  data_quality_score,
  now()
from rows
on conflict (company_id) do update
  set verified_name = coalesce(excluded.verified_name, public.company_profiles.verified_name),
      homepage_url = coalesce(excluded.homepage_url, public.company_profiles.homepage_url),
      careers_page_url = coalesce(excluded.careers_page_url, public.company_profiles.careers_page_url),
      address = coalesce(excluded.address, public.company_profiles.address),
      stock_code = coalesce(excluded.stock_code, public.company_profiles.stock_code),
      dart_corp_code = coalesce(excluded.dart_corp_code, public.company_profiles.dart_corp_code),
      summary = coalesce(excluded.summary, public.company_profiles.summary),
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();


insert into public.company_sources (
  company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
)
values
(1, 'A_GOV_OFFICIAL', 'opendart_company_profile', '강남 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00671899', 'OpenDART', '{"endpoint":"company.json","corp_code":"00671899","dart_name":"주식회사강남","stock_code":null,"homepage_url":"https://www.knsol.co.kr"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(2, 'A_GOV_OFFICIAL', 'opendart_company_profile', '고려화공 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00227634', 'OpenDART', '{"endpoint":"company.json","corp_code":"00227634","dart_name":"고려화공(주)","stock_code":null,"homepage_url":null}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(3, 'A_GOV_OFFICIAL', 'opendart_company_profile', '광림 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00103635', 'OpenDART', '{"endpoint":"company.json","corp_code":"00103635","dart_name":"(주)광림","stock_code":"014200","homepage_url":"https://www.kanglim.com"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(4, 'A_GOV_OFFICIAL', 'opendart_company_profile', '기아 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00106641', 'OpenDART', '{"endpoint":"company.json","corp_code":"00106641","dart_name":"기아(주)","stock_code":"000270","homepage_url":"https://www.kia.co.kr"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(5, 'A_GOV_OFFICIAL', 'opendart_company_profile', '다산기공 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00809438', 'OpenDART', '{"endpoint":"company.json","corp_code":"00809438","dart_name":"다산기공(주)","stock_code":null,"homepage_url":null}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(6, 'A_GOV_OFFICIAL', 'opendart_company_profile', '다윈프릭션 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00863436', 'OpenDART', '{"endpoint":"company.json","corp_code":"00863436","dart_name":"주식회사 다윈프릭션","stock_code":null,"homepage_url":"https://www.dawinf.co.kr"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(7, 'A_GOV_OFFICIAL', 'opendart_company_profile', '단암시스템즈 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00459279', 'OpenDART', '{"endpoint":"company.json","corp_code":"00459279","dart_name":"단암시스템즈주식회사","stock_code":null,"homepage_url":null}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(8, 'A_GOV_OFFICIAL', 'opendart_company_profile', '대명 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00172361', 'OpenDART', '{"endpoint":"company.json","corp_code":"00172361","dart_name":"주식회사 대명","stock_code":null,"homepage_url":null}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(9, 'A_GOV_OFFICIAL', 'opendart_company_profile', '대신금속 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00828239', 'OpenDART', '{"endpoint":"company.json","corp_code":"00828239","dart_name":"(주)대신금속","stock_code":null,"homepage_url":null}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(10, 'A_GOV_OFFICIAL', 'opendart_company_profile', '대양전기공업 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00111193', 'OpenDART', '{"endpoint":"company.json","corp_code":"00111193","dart_name":"대양전기공업(주)","stock_code":"108380","homepage_url":"https://daeyang.co.kr"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(11, 'A_GOV_OFFICIAL', 'opendart_company_profile', '대영에스텍 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00867308', 'OpenDART', '{"endpoint":"company.json","corp_code":"00867308","dart_name":"(주)대영에스텍","stock_code":null,"homepage_url":null}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(12, 'A_GOV_OFFICIAL', 'opendart_company_profile', '대한항공 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00113526', 'OpenDART', '{"endpoint":"company.json","corp_code":"00113526","dart_name":"(주)대한항공","stock_code":"003490","homepage_url":"https://www.koreanair.com"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(13, 'A_GOV_OFFICIAL', 'opendart_company_profile', '덕산넵코어스 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00960623', 'OpenDART', '{"endpoint":"company.json","corp_code":"00960623","dart_name":"덕산넵코어스주식회사","stock_code":null,"homepage_url":null}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(14, 'A_GOV_OFFICIAL', 'opendart_company_profile', '데크카본 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=01040555', 'OpenDART', '{"endpoint":"company.json","corp_code":"01040555","dart_name":"(주)데크카본","stock_code":null,"homepage_url":"https://www.dacc21.co.kr"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(15, 'A_GOV_OFFICIAL', 'opendart_company_profile', '동양정공 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00455343', 'OpenDART', '{"endpoint":"company.json","corp_code":"00455343","dart_name":"동양정공(주)","stock_code":null,"homepage_url":null}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(16, 'A_GOV_OFFICIAL', 'opendart_company_profile', '동인광학 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00926212', 'OpenDART', '{"endpoint":"company.json","corp_code":"00926212","dart_name":"주식회사 동인광학","stock_code":null,"homepage_url":"https://www.donginoptical.com"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(17, 'A_GOV_OFFICIAL', 'opendart_company_profile', '두산에너빌리티 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00159616', 'OpenDART', '{"endpoint":"company.json","corp_code":"00159616","dart_name":"두산에너빌리티(주)","stock_code":"034020","homepage_url":"https://www.doosanenerbility.com/kr"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(18, 'A_GOV_OFFICIAL', 'opendart_company_profile', '두원중공업 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00119724', 'OpenDART', '{"endpoint":"company.json","corp_code":"00119724","dart_name":"두원중공업 주식회사","stock_code":null,"homepage_url":"https://www.doowonhi.com"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(19, 'A_GOV_OFFICIAL', 'opendart_company_profile', '엠엔씨솔루션 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00361743', 'OpenDART', '{"endpoint":"company.json","corp_code":"00361743","dart_name":"(주)씨솔루션","stock_code":null,"homepage_url":null}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(20, 'A_GOV_OFFICIAL', 'opendart_company_profile', '미래엠텍 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00879729', 'OpenDART', '{"endpoint":"company.json","corp_code":"00879729","dart_name":"(주)  미래  엠  텍","stock_code":null,"homepage_url":"https://www.miraemtech.com"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(21, 'A_GOV_OFFICIAL', 'opendart_company_profile', '비츠로밀텍 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=01263077', 'OpenDART', '{"endpoint":"company.json","corp_code":"01263077","dart_name":"(주) 비츠로밀텍","stock_code":null,"homepage_url":"https://vitzromiltech.com"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(22, 'A_GOV_OFFICIAL', 'opendart_company_profile', '빅텍 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00385363', 'OpenDART', '{"endpoint":"company.json","corp_code":"00385363","dart_name":"(주)빅텍","stock_code":"065450","homepage_url":"https://www.victek.co.kr"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(23, 'A_GOV_OFFICIAL', 'opendart_company_profile', '삼양정밀화학 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=01834079', 'OpenDART', '{"endpoint":"company.json","corp_code":"01834079","dart_name":"(주)삼양정밀화학","stock_code":null,"homepage_url":"https://syfc.co.kr"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(24, 'A_GOV_OFFICIAL', 'opendart_company_profile', '삼양컴텍 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00141583', 'OpenDART', '{"endpoint":"company.json","corp_code":"00141583","dart_name":"주식회사 삼양컴텍","stock_code":"484590","homepage_url":"https://samyangct.com"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(25, 'A_GOV_OFFICIAL', 'opendart_company_profile', '삼양화학공업 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00127088', 'OpenDART', '{"endpoint":"company.json","corp_code":"00127088","dart_name":"삼양화학공업(주)","stock_code":null,"homepage_url":null}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(26, 'A_GOV_OFFICIAL', 'opendart_company_profile', '삼영이엔씨 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00288343', 'OpenDART', '{"endpoint":"company.json","corp_code":"00288343","dart_name":"삼영이엔씨(주)","stock_code":"065570","homepage_url":"https://www.samyungenc.com"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(27, 'A_GOV_OFFICIAL', 'opendart_company_profile', '삼정터빈 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00221560', 'OpenDART', '{"endpoint":"company.json","corp_code":"00221560","dart_name":"주식회사 삼정터빈","stock_code":null,"homepage_url":"https://www.turbine.co.kr"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(28, 'A_GOV_OFFICIAL', 'opendart_company_profile', '삼정티비엠 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=02004815', 'OpenDART', '{"endpoint":"company.json","corp_code":"02004815","dart_name":"주식회사티비엠","stock_code":null,"homepage_url":"https://www.aerospacetbm.com"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(29, 'A_GOV_OFFICIAL', 'opendart_company_profile', '삼주기업 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=01138832', 'OpenDART', '{"endpoint":"company.json","corp_code":"01138832","dart_name":"(주)삼주기업","stock_code":null,"homepage_url":"https://www.samjurubber.com"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(30, 'A_GOV_OFFICIAL', 'opendart_company_profile', '성진테크윈 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=01251027', 'OpenDART', '{"endpoint":"company.json","corp_code":"01251027","dart_name":"성진테크윈","stock_code":null,"homepage_url":"https://www.switch-vr.com"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(31, 'A_GOV_OFFICIAL', 'opendart_company_profile', '세아항공방산소재 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00456698', 'OpenDART', '{"endpoint":"company.json","corp_code":"00456698","dart_name":"주식회사 세아항공방산소재","stock_code":null,"homepage_url":null}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(32, 'A_GOV_OFFICIAL', 'opendart_company_profile', '스페코 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00136165', 'OpenDART', '{"endpoint":"company.json","corp_code":"00136165","dart_name":"(주)스페코","stock_code":"013810","homepage_url":"https://www.speco.co.kr"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(33, 'A_GOV_OFFICIAL', 'opendart_company_profile', '시공사 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00564836', 'OpenDART', '{"endpoint":"company.json","corp_code":"00564836","dart_name":"(주)시공사","stock_code":null,"homepage_url":"https://sigongsa.koreasme.com"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(34, 'A_GOV_OFFICIAL', 'opendart_company_profile', '신정개발특장차 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00914156', 'OpenDART', '{"endpoint":"company.json","corp_code":"00914156","dart_name":"신정개발특장차(주)","stock_code":null,"homepage_url":"https://www.shinjeong.co.kr"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(35, 'A_GOV_OFFICIAL', 'opendart_company_profile', '쎄트렉아이 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00449254', 'OpenDART', '{"endpoint":"company.json","corp_code":"00449254","dart_name":"주식회사쎄트렉아이","stock_code":"099320","homepage_url":"https://www.satreci.com"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(36, 'A_GOV_OFFICIAL', 'opendart_company_profile', '씨앤지 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00677662', 'OpenDART', '{"endpoint":"company.json","corp_code":"00677662","dart_name":"주식회사 씨앤지","stock_code":null,"homepage_url":"https://www.ecng.co.kr"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(37, 'A_GOV_OFFICIAL', 'opendart_company_profile', '아이쓰리시스템 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00612489', 'OpenDART', '{"endpoint":"company.json","corp_code":"00612489","dart_name":"아이쓰리시스템(주)","stock_code":"214430","homepage_url":"https://www.i3system.com"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(38, 'A_GOV_OFFICIAL', 'opendart_company_profile', '아이펙 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=01004298', 'OpenDART', '{"endpoint":"company.json","corp_code":"01004298","dart_name":"아이펙스 주식회사","stock_code":null,"homepage_url":null}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(39, 'A_GOV_OFFICIAL', 'opendart_company_profile', '에비오시스테크놀러지스 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=01546305', 'OpenDART', '{"endpoint":"company.json","corp_code":"01546305","dart_name":"주식회사 에비오시스 테크놀러지스","stock_code":null,"homepage_url":"https://www.aviosystech.com"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(40, 'A_GOV_OFFICIAL', 'opendart_company_profile', '에이치케이씨(HKC) OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00235183', 'OpenDART', '{"endpoint":"company.json","corp_code":"00235183","dart_name":"(주)에이치케이","stock_code":"044780","homepage_url":"https://www.hk-global.com"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(41, 'A_GOV_OFFICIAL', 'opendart_company_profile', '연합정밀 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00140371', 'OpenDART', '{"endpoint":"company.json","corp_code":"00140371","dart_name":"연합정밀주식회사","stock_code":null,"homepage_url":"https://www.yeonhab.co.kr"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(42, 'A_GOV_OFFICIAL', 'opendart_company_profile', '우경광학 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=01564310', 'OpenDART', '{"endpoint":"company.json","corp_code":"01564310","dart_name":"주식회사우경광학","stock_code":null,"homepage_url":"https://www.wkoptics.com"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(43, 'A_GOV_OFFICIAL', 'opendart_company_profile', '우리별 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00767682', 'OpenDART', '{"endpoint":"company.json","corp_code":"00767682","dart_name":"주식회사 우리별","stock_code":null,"homepage_url":"https://www.wooribyul.co.kr"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(44, 'A_GOV_OFFICIAL', 'opendart_company_profile', '유아이헬리콥터 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00619233', 'OpenDART', '{"endpoint":"company.json","corp_code":"00619233","dart_name":"주식회사 유아이헬리콥터","stock_code":null,"homepage_url":null}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(45, 'A_GOV_OFFICIAL', 'opendart_company_profile', '유텍 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=01552689', 'OpenDART', '{"endpoint":"company.json","corp_code":"01552689","dart_name":"(주)유텍","stock_code":null,"homepage_url":"https://www.utech.co.kr"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(46, 'A_GOV_OFFICIAL', 'opendart_company_profile', '은성사 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00145349', 'OpenDART', '{"endpoint":"company.json","corp_code":"00145349","dart_name":"주식회사 은성사","stock_code":null,"homepage_url":"https://www.silstar.co.kr"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(47, 'A_GOV_OFFICIAL', 'opendart_company_profile', '이오시스템 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=01498974', 'OpenDART', '{"endpoint":"company.json","corp_code":"01498974","dart_name":"큐리옥스바이오시스템즈(주)","stock_code":"445680","homepage_url":"https://curiox.co.kr"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(48, 'A_GOV_OFFICIAL', 'opendart_company_profile', '이화전기공업 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00145738', 'OpenDART', '{"endpoint":"company.json","corp_code":"00145738","dart_name":"이화전기공업(주)","stock_code":"024810","homepage_url":"https://www.eti21.com"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(49, 'A_GOV_OFFICIAL', 'opendart_company_profile', '인소팩 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00959292', 'OpenDART', '{"endpoint":"company.json","corp_code":"00959292","dart_name":"인소팩주식회사","stock_code":null,"homepage_url":"https://www.insopack.co.kr"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(50, 'A_GOV_OFFICIAL', 'opendart_company_profile', '스페이스프로 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00160597', 'OpenDART', '{"endpoint":"company.json","corp_code":"00160597","dart_name":"주식회사 스페이스프로","stock_code":null,"homepage_url":"https://www.spacepro.co.kr"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(51, 'A_GOV_OFFICIAL', 'opendart_company_profile', '인피니티에코 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00626109', 'OpenDART', '{"endpoint":"company.json","corp_code":"00626109","dart_name":"(주)인피니티","stock_code":null,"homepage_url":"https://www.dktec.co.kr"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(52, 'A_GOV_OFFICIAL', 'opendart_company_profile', '진영정기 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00150581', 'OpenDART', '{"endpoint":"company.json","corp_code":"00150581","dart_name":"주식회사 진영정기","stock_code":null,"homepage_url":"https://www.kojin.co.kr"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(53, 'A_GOV_OFFICIAL', 'opendart_company_profile', '캐스 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00652946', 'OpenDART', '{"endpoint":"company.json","corp_code":"00652946","dart_name":"(주)캐스","stock_code":null,"homepage_url":"https://www.kaes.biz"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(54, 'A_GOV_OFFICIAL', 'opendart_company_profile', '코리아디펜스인더스트리 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=01511567', 'OpenDART', '{"endpoint":"company.json","corp_code":"01511567","dart_name":"(주)코리아 디펜스 인더스트리","stock_code":null,"homepage_url":null}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(55, 'A_GOV_OFFICIAL', 'opendart_company_profile', '코오롱스테이스웍스 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00152862', 'OpenDART', '{"endpoint":"company.json","corp_code":"00152862","dart_name":"(주)코오롱","stock_code":"002020","homepage_url":"https://www.kolon.com"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(56, 'A_GOV_OFFICIAL', 'opendart_company_profile', '티에스택 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=01154575', 'OpenDART', '{"endpoint":"company.json","corp_code":"01154575","dart_name":"티에스주식회사","stock_code":null,"homepage_url":"https://www.tsglobal.co.kr"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(57, 'A_GOV_OFFICIAL', 'opendart_company_profile', '퍼스텍 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00148522', 'OpenDART', '{"endpoint":"company.json","corp_code":"00148522","dart_name":"퍼스텍(주)","stock_code":"010820","homepage_url":"https://www.firsteccom.co.kr"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(58, 'A_GOV_OFFICIAL', 'opendart_company_profile', '평화산업 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00573579', 'OpenDART', '{"endpoint":"company.json","corp_code":"00573579","dart_name":"평화산업(주)","stock_code":"090080","homepage_url":"https://www.ph.co.kr"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(59, 'A_GOV_OFFICIAL', 'opendart_company_profile', '풍산 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00684714', 'OpenDART', '{"endpoint":"company.json","corp_code":"00684714","dart_name":"(주)풍산","stock_code":"103140","homepage_url":"https://www.poongsan.co.kr"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(60, 'A_GOV_OFFICIAL', 'opendart_company_profile', '풍산FNS OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00165219', 'OpenDART', '{"endpoint":"company.json","corp_code":"00165219","dart_name":"(주)풍산에프앤에스","stock_code":null,"homepage_url":"https://www.poongsanfns.co.kr"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(61, 'A_GOV_OFFICIAL', 'opendart_company_profile', '한국특수전지 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00249016', 'OpenDART', '{"endpoint":"company.json","corp_code":"00249016","dart_name":"한국특수전지(주)","stock_code":null,"homepage_url":"https://www.ksbatteries.com"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(62, 'A_GOV_OFFICIAL', 'opendart_company_profile', '한국항공우주산업 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00309503', 'OpenDART', '{"endpoint":"company.json","corp_code":"00309503","dart_name":"한국항공우주산업(주)","stock_code":"047810","homepage_url":"https://www.koreaaero.com"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(63, 'A_GOV_OFFICIAL', 'opendart_company_profile', '한일단조공업 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00162832', 'OpenDART', '{"endpoint":"company.json","corp_code":"00162832","dart_name":"한일단조공업(주)","stock_code":"024740","homepage_url":"https://www.hifg.co.kr"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(64, 'A_GOV_OFFICIAL', 'opendart_company_profile', '한컴라이프케어 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00534598', 'OpenDART', '{"endpoint":"company.json","corp_code":"00534598","dart_name":"주식회사 한컴라이프케어","stock_code":"372910","homepage_url":"https://www.hancomlifecare.com"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(65, 'A_GOV_OFFICIAL', 'opendart_company_profile', '한화오션 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00111704', 'OpenDART', '{"endpoint":"company.json","corp_code":"00111704","dart_name":"한화오션(주)","stock_code":"042660","homepage_url":"https://www.hanwhaocean.com/pub/main/index.do"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(66, 'A_GOV_OFFICIAL', 'opendart_company_profile', '한화시스템 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00339391', 'OpenDART', '{"endpoint":"company.json","corp_code":"00339391","dart_name":"한화시스템(주)","stock_code":"272210","homepage_url":"https://hanwhasystems.com"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(67, 'A_GOV_OFFICIAL', 'opendart_company_profile', '한화에어로스페이스 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00126566', 'OpenDART', '{"endpoint":"company.json","corp_code":"00126566","dart_name":"한화에어로스페이스(주)","stock_code":"012450","homepage_url":"https://www.hanwhaaerospace.com"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(68, 'A_GOV_OFFICIAL', 'opendart_company_profile', '현대로템 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00302926', 'OpenDART', '{"endpoint":"company.json","corp_code":"00302926","dart_name":"현대로템(주)","stock_code":"064350","homepage_url":"https://www.hyundai-rotem.co.kr"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(69, 'A_GOV_OFFICIAL', 'opendart_company_profile', '현대위아 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00106623', 'OpenDART', '{"endpoint":"company.json","corp_code":"00106623","dart_name":"현대위아(주)","stock_code":"011210","homepage_url":"https://www.hyundai-wia.com"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(70, 'A_GOV_OFFICIAL', 'opendart_company_profile', '현대제이콤 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00409016', 'OpenDART', '{"endpoint":"company.json","corp_code":"00409016","dart_name":"(주)현대제이콤","stock_code":null,"homepage_url":null}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(71, 'A_GOV_OFFICIAL', 'opendart_company_profile', '현대트랜시스 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00302634', 'OpenDART', '{"endpoint":"company.json","corp_code":"00302634","dart_name":"현대트랜시스주식회사","stock_code":null,"homepage_url":"https://www.hyundai-transys.com"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(73, 'A_GOV_OFFICIAL', 'opendart_company_profile', '효성중공업 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=01316245', 'OpenDART', '{"endpoint":"company.json","corp_code":"01316245","dart_name":"효성중공업(주)","stock_code":"298040","homepage_url":"https://www.hyosungheavyindustries.com"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(74, 'A_GOV_OFFICIAL', 'opendart_company_profile', '휴니드테크놀러지스 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00111421', 'OpenDART', '{"endpoint":"company.json","corp_code":"00111421","dart_name":"(주)휴니드테크놀러지스","stock_code":"005870","homepage_url":"https://www.huneed.com"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(75, 'A_GOV_OFFICIAL', 'opendart_company_profile', 'HD현대인프라코어 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00344287', 'OpenDART', '{"endpoint":"company.json","corp_code":"00344287","dart_name":"에이치디현대인프라코어(주)","stock_code":"042670","homepage_url":"https://www.hd-infracore.com"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(76, 'A_GOV_OFFICIAL', 'opendart_company_profile', 'HD현대중공업 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=01169346', 'OpenDART', '{"endpoint":"company.json","corp_code":"01169346","dart_name":"에이치디현대중공업모스 주식회사","stock_code":null,"homepage_url":null}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(77, 'A_GOV_OFFICIAL', 'opendart_company_profile', 'HJ중공업 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00865115', 'OpenDART', '{"endpoint":"company.json","corp_code":"00865115","dart_name":"(주)에이치제이","stock_code":null,"homepage_url":"https://www.hjlite.com"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(78, 'A_GOV_OFFICIAL', 'opendart_company_profile', 'LIG넥스원 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00576619', 'OpenDART', '{"endpoint":"company.json","corp_code":"00576619","dart_name":"주식회사 엘아이지","stock_code":null,"homepage_url":"https://www.ligcorp.com"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(79, 'A_GOV_OFFICIAL', 'opendart_company_profile', 'LS엠트론 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00597047', 'OpenDART', '{"endpoint":"company.json","corp_code":"00597047","dart_name":"(주)엠트론","stock_code":null,"homepage_url":"https://www.mtron.net"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(82, 'A_GOV_OFFICIAL', 'opendart_company_profile', 'SK오션플랜트 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=01096068', 'OpenDART', '{"endpoint":"company.json","corp_code":"01096068","dart_name":"케이오 주식회사","stock_code":null,"homepage_url":null}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(83, 'A_GOV_OFFICIAL', 'opendart_company_profile', 'SNT모티브 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00943918', 'OpenDART', '{"endpoint":"company.json","corp_code":"00943918","dart_name":"주식회사 에스앤티","stock_code":null,"homepage_url":null}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(84, 'A_GOV_OFFICIAL', 'opendart_company_profile', 'SNT다이내믹스 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00943918', 'OpenDART', '{"endpoint":"company.json","corp_code":"00943918","dart_name":"주식회사 에스앤티","stock_code":null,"homepage_url":null}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs'),
(85, 'A_GOV_OFFICIAL', 'opendart_company_profile', 'STX엔진 OpenDART 기업개황', 'https://opendart.fss.or.kr/api/company.json?corp_code=00480455', 'OpenDART', '{"endpoint":"company.json","corp_code":"00480455","dart_name":"STX엔진(주)","stock_code":"077970","homepage_url":"https://www.stxengine.co.kr"}'::jsonb, 'Generated by scripts/generate-company-web-enrichment-sql.mjs')
on conflict (company_id, source_type, source_url) do update
  set title = excluded.title,
      publisher = excluded.publisher,
      evidence = excluded.evidence,
      source_grade = excluded.source_grade,
      retrieved_at = now(),
      notes = excluded.notes;


insert into public.company_sources (
  company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
)
values
(3, 'B_COMPANY_OFFICIAL', 'official_homepage_career_link', '광림 공식 채용 페이지', 'https://www.kanglim.com/company/recruit', '광림', '{"homepage_url":"https://www.kanglim.com","detected_from":"https://www.kanglim.com/","link_label":"인재채용"}'::jsonb, 'Detected from official homepage links by scripts/generate-company-web-enrichment-sql.mjs'),
(12, 'B_COMPANY_OFFICIAL', 'official_homepage_career_link', '대한항공 공식 채용 페이지', 'https://www.koreanair.com/recruit', '대한항공', '{"homepage_url":"https://www.koreanair.com","detected_from":"https://www.koreanair.com/","link_label":"/recruit"}'::jsonb, 'Detected from official homepage links by scripts/generate-company-web-enrichment-sql.mjs'),
(17, 'B_COMPANY_OFFICIAL', 'official_homepage_career_link', '두산에너빌리티 공식 채용 페이지', 'https://www.doosanenerbility.com/kr/employment/talent_02', '두산에너빌리티', '{"homepage_url":"https://www.doosanenerbility.com/kr","detected_from":"https://www.doosanenerbility.com/kr","link_label":"채용"}'::jsonb, 'Detected from official homepage links by scripts/generate-company-web-enrichment-sql.mjs'),
(18, 'B_COMPANY_OFFICIAL', 'official_homepage_career_link', '두원중공업 공식 채용 페이지', 'https://www.saramin.co.kr/zf_user/company-info/view-inner-recruit?csn=RHZsVTQ4cGZPWjVuZXJoOEptS095dz09', '두원중공업', '{"homepage_url":"https://www.doowonhi.com","detected_from":"https://www.doowonhi.com/kr/index.php","link_label":"채용공고"}'::jsonb, 'Detected from official homepage links by scripts/generate-company-web-enrichment-sql.mjs'),
(24, 'B_COMPANY_OFFICIAL', 'official_homepage_career_link', '삼양컴텍 공식 채용 페이지', 'https://samyangct.com/recruit', '삼양컴텍', '{"homepage_url":"https://samyangct.com","detected_from":"https://samyangct.com/","link_label":"/recruit"}'::jsonb, 'Detected from official homepage links by scripts/generate-company-web-enrichment-sql.mjs'),
(35, 'B_COMPANY_OFFICIAL', 'official_homepage_career_link', '쎄트렉아이 공식 채용 페이지', 'https://satreci.recruiter.co.kr/career/home', '쎄트렉아이', '{"homepage_url":"https://www.satreci.com","detected_from":"https://www.satreci.com/","link_label":"인재채용"}'::jsonb, 'Detected from official homepage links by scripts/generate-company-web-enrichment-sql.mjs'),
(36, 'B_COMPANY_OFFICIAL', 'official_homepage_career_link', '씨앤지 공식 채용 페이지', 'https://www.ecng.co.kr/recruit', '씨앤지', '{"homepage_url":"https://www.ecng.co.kr","detected_from":"https://www.ecng.co.kr/","link_label":"/recruit"}'::jsonb, 'Detected from official homepage links by scripts/generate-company-web-enrichment-sql.mjs'),
(37, 'B_COMPANY_OFFICIAL', 'official_homepage_career_link', '아이쓰리시스템 공식 채용 페이지', 'http://i3system.com/%ec%9d%b8%ec%9e%ac%ec%b1%84%ec%9a%a9/%ec%b1%84%ec%9a%a9%ec%a0%95%eb%b3%b4', '아이쓰리시스템', '{"homepage_url":"https://www.i3system.com","detected_from":"https://i3system.com/","link_label":"채용정보"}'::jsonb, 'Detected from official homepage links by scripts/generate-company-web-enrichment-sql.mjs'),
(39, 'B_COMPANY_OFFICIAL', 'official_homepage_career_link', '에비오시스테크놀러지스 공식 채용 페이지', 'https://www.aviosystech.com/page/sub04-1.php', '에비오시스테크놀러지스', '{"homepage_url":"https://www.aviosystech.com","detected_from":"https://www.aviosystech.com/","link_label":"Recruit"}'::jsonb, 'Detected from official homepage links by scripts/generate-company-web-enrichment-sql.mjs'),
(40, 'B_COMPANY_OFFICIAL', 'official_homepage_career_link', '에이치케이씨(HKC) 공식 채용 페이지', 'https://www.hk-global.com/ko/recruit/want.html', '에이치케이씨(HKC)', '{"homepage_url":"https://www.hk-global.com","detected_from":"https://www.hk-global.com/","link_label":"채용정보"}'::jsonb, 'Detected from official homepage links by scripts/generate-company-web-enrichment-sql.mjs'),
(46, 'B_COMPANY_OFFICIAL', 'official_homepage_career_link', '은성사 공식 채용 페이지', 'https://www.silstar.co.kr/recruit', '은성사', '{"homepage_url":"https://www.silstar.co.kr","detected_from":"https://www.silstar.co.kr/","link_label":"/recruit"}'::jsonb, 'Detected from official homepage links by scripts/generate-company-web-enrichment-sql.mjs'),
(47, 'B_COMPANY_OFFICIAL', 'official_homepage_career_link', '이오시스템 공식 채용 페이지', 'https://curiox.co.kr/sub/careers/recruitment.asp', '이오시스템', '{"homepage_url":"https://curiox.co.kr","detected_from":"https://curiox.co.kr/","link_label":"인재채용"}'::jsonb, 'Detected from official homepage links by scripts/generate-company-web-enrichment-sql.mjs'),
(50, 'B_COMPANY_OFFICIAL', 'official_homepage_career_link', '스페이스프로 공식 채용 페이지', 'https://www.spacepro.co.kr/bbs/board.php?bo_table=careers', '스페이스프로', '{"homepage_url":"https://www.spacepro.co.kr","detected_from":"https://www.spacepro.co.kr/","link_label":"채용공고"}'::jsonb, 'Detected from official homepage links by scripts/generate-company-web-enrichment-sql.mjs'),
(53, 'B_COMPANY_OFFICIAL', 'official_homepage_career_link', '캐스 공식 채용 페이지', 'https://www.kaes.biz/recruit', '캐스', '{"homepage_url":"https://www.kaes.biz","detected_from":"https://www.kaes.biz/","link_label":"/recruit"}'::jsonb, 'Detected from official homepage links by scripts/generate-company-web-enrichment-sql.mjs'),
(57, 'B_COMPANY_OFFICIAL', 'official_homepage_career_link', '퍼스텍 공식 채용 페이지', 'https://www.firsteccom.co.kr/recruit/recruit_01', '퍼스텍', '{"homepage_url":"https://www.firsteccom.co.kr","detected_from":"https://www.firsteccom.co.kr/","link_label":"인재채용"}'::jsonb, 'Detected from official homepage links by scripts/generate-company-web-enrichment-sql.mjs'),
(59, 'B_COMPANY_OFFICIAL', 'official_homepage_career_link', '풍산 공식 채용 페이지', 'https://www.poongsan.co.kr/recruit/disclosure/information', '풍산', '{"homepage_url":"https://www.poongsan.co.kr","detected_from":"https://www.poongsan.co.kr/main","link_label":"채용정보"}'::jsonb, 'Detected from official homepage links by scripts/generate-company-web-enrichment-sql.mjs'),
(60, 'B_COMPANY_OFFICIAL', 'official_homepage_career_link', '풍산FNS 공식 채용 페이지', 'https://www.poongsanfns.co.kr/career', '풍산FNS', '{"homepage_url":"https://www.poongsanfns.co.kr","detected_from":"https://www.poongsanfns.co.kr/","link_label":"채용정보"}'::jsonb, 'Detected from official homepage links by scripts/generate-company-web-enrichment-sql.mjs'),
(62, 'B_COMPANY_OFFICIAL', 'official_homepage_career_link', '한국항공우주산업 공식 채용 페이지', 'https://www.koreaaero.com/recruit', '한국항공우주산업', '{"homepage_url":"https://www.koreaaero.com","detected_from":"https://www.koreaaero.com/","link_label":"/recruit"}'::jsonb, 'Detected from official homepage links by scripts/generate-company-web-enrichment-sql.mjs'),
(65, 'B_COMPANY_OFFICIAL', 'official_homepage_career_link', '한화오션 공식 채용 페이지', 'https://www.hanwhaocean.com/careers/ri', '한화오션', '{"homepage_url":"https://www.hanwhaocean.com/pub/main/index.do","detected_from":"https://www.hanwhaocean.com/","link_label":"채용안내"}'::jsonb, 'Detected from official homepage links by scripts/generate-company-web-enrichment-sql.mjs'),
(67, 'B_COMPANY_OFFICIAL', 'official_homepage_career_link', '한화에어로스페이스 공식 채용 페이지', 'https://www.hanwhaaerospace.com/kor/careers/recruit.do', '한화에어로스페이스', '{"homepage_url":"https://www.hanwhaaerospace.com","detected_from":"https://www.hanwhaaerospace.com/kor/index.do","link_label":"채용안내"}'::jsonb, 'Detected from official homepage links by scripts/generate-company-web-enrichment-sql.mjs'),
(69, 'B_COMPANY_OFFICIAL', 'official_homepage_career_link', '현대위아 공식 채용 페이지', 'https://www.hyundai-wia.com/recruit', '현대위아', '{"homepage_url":"https://www.hyundai-wia.com","detected_from":"https://www.hyundai-wia.com/","link_label":"/recruit"}'::jsonb, 'Detected from official homepage links by scripts/generate-company-web-enrichment-sql.mjs'),
(71, 'B_COMPANY_OFFICIAL', 'official_homepage_career_link', '현대트랜시스 공식 채용 페이지', 'https://www.hyundai-transys.com/ko/careers/jobs.do', '현대트랜시스', '{"homepage_url":"https://www.hyundai-transys.com","detected_from":"https://www.hyundai-transys.com/ko/main.do","link_label":"인재채용"}'::jsonb, 'Detected from official homepage links by scripts/generate-company-web-enrichment-sql.mjs'),
(73, 'B_COMPANY_OFFICIAL', 'official_homepage_career_link', '효성중공업 공식 채용 페이지', 'https://www.hyosungheavyindustries.com/kr/company/recruitment/ideal-talent', '효성중공업', '{"homepage_url":"https://www.hyosungheavyindustries.com","detected_from":"https://www.hyosungheavyindustries.com/kr","link_label":"인재채용"}'::jsonb, 'Detected from official homepage links by scripts/generate-company-web-enrichment-sql.mjs'),
(74, 'B_COMPANY_OFFICIAL', 'official_homepage_career_link', '휴니드테크놀러지스 공식 채용 페이지', 'https://www.huneed.com/%EC%B1%84%EC%9A%A9%EA%B3%B5%EA%B3%A0', '휴니드테크놀러지스', '{"homepage_url":"https://www.huneed.com","detected_from":"https://www.huneed.com/","link_label":"채용공고"}'::jsonb, 'Detected from official homepage links by scripts/generate-company-web-enrichment-sql.mjs'),
(77, 'B_COMPANY_OFFICIAL', 'official_homepage_career_link', 'HJ중공업 공식 채용 페이지', 'https://www.hjlite.com/recruit', 'HJ중공업', '{"homepage_url":"https://www.hjlite.com","detected_from":"https://www.hjlite.com/","link_label":"/recruit"}'::jsonb, 'Detected from official homepage links by scripts/generate-company-web-enrichment-sql.mjs'),
(78, 'B_COMPANY_OFFICIAL', 'official_homepage_career_link', 'LIG넥스원 공식 채용 페이지', 'https://www.ligcorp.com/recruit', 'LIG넥스원', '{"homepage_url":"https://www.ligcorp.com","detected_from":"https://www.ligcorp.com/web/main/index.do","link_label":"/recruit"}'::jsonb, 'Detected from official homepage links by scripts/generate-company-web-enrichment-sql.mjs'),
(85, 'B_COMPANY_OFFICIAL', 'official_homepage_career_link', 'STX엔진 공식 채용 페이지', 'https://www.stxengine.co.kr/kor/html/recruit/talent.aspx', 'STX엔진', '{"homepage_url":"https://www.stxengine.co.kr","detected_from":"https://www.stxengine.co.kr/kor/Default.aspx","link_label":"채용정보"}'::jsonb, 'Detected from official homepage links by scripts/generate-company-web-enrichment-sql.mjs')
on conflict (company_id, source_type, source_url) do update
  set title = excluded.title,
      publisher = excluded.publisher,
      evidence = excluded.evidence,
      source_grade = excluded.source_grade,
      retrieved_at = now(),
      notes = excluded.notes;

with rows(company_id, careers_page_url) as (
  values
(3, 'https://www.kanglim.com/company/recruit'),
(12, 'https://www.koreanair.com/recruit'),
(17, 'https://www.doosanenerbility.com/kr/employment/talent_02'),
(18, 'https://www.saramin.co.kr/zf_user/company-info/view-inner-recruit?csn=RHZsVTQ4cGZPWjVuZXJoOEptS095dz09'),
(24, 'https://samyangct.com/recruit'),
(35, 'https://satreci.recruiter.co.kr/career/home'),
(36, 'https://www.ecng.co.kr/recruit'),
(37, 'http://i3system.com/%ec%9d%b8%ec%9e%ac%ec%b1%84%ec%9a%a9/%ec%b1%84%ec%9a%a9%ec%a0%95%eb%b3%b4'),
(39, 'https://www.aviosystech.com/page/sub04-1.php'),
(40, 'https://www.hk-global.com/ko/recruit/want.html'),
(46, 'https://www.silstar.co.kr/recruit'),
(47, 'https://curiox.co.kr/sub/careers/recruitment.asp'),
(50, 'https://www.spacepro.co.kr/bbs/board.php?bo_table=careers'),
(53, 'https://www.kaes.biz/recruit'),
(57, 'https://www.firsteccom.co.kr/recruit/recruit_01'),
(59, 'https://www.poongsan.co.kr/recruit/disclosure/information'),
(60, 'https://www.poongsanfns.co.kr/career'),
(62, 'https://www.koreaaero.com/recruit'),
(65, 'https://www.hanwhaocean.com/careers/ri'),
(67, 'https://www.hanwhaaerospace.com/kor/careers/recruit.do'),
(69, 'https://www.hyundai-wia.com/recruit'),
(71, 'https://www.hyundai-transys.com/ko/careers/jobs.do'),
(73, 'https://www.hyosungheavyindustries.com/kr/company/recruitment/ideal-talent'),
(74, 'https://www.huneed.com/%EC%B1%84%EC%9A%A9%EA%B3%B5%EA%B3%A0'),
(77, 'https://www.hjlite.com/recruit'),
(78, 'https://www.ligcorp.com/recruit'),
(85, 'https://www.stxengine.co.kr/kor/html/recruit/talent.aspx')
)
update public.companies
set careers_page_url = rows.careers_page_url
from rows
where public.companies.id = rows.company_id;

with rows(company_id, title, job_function, posting_url, raw) as (
  values
(3, '공식 채용 페이지', '기동 분야 채용 정보 확인', 'https://www.kanglim.com/company/recruit', '{"kind":"official_career_page_pointer","homepage_url":"https://www.kanglim.com","link_label":"인재채용"}'::jsonb),
(12, '공식 채용 페이지', '항공유도 분야 채용 정보 확인', 'https://www.koreanair.com/recruit', '{"kind":"official_career_page_pointer","homepage_url":"https://www.koreanair.com","link_label":"/recruit"}'::jsonb),
(17, '공식 채용 페이지', '기동 분야 채용 정보 확인', 'https://www.doosanenerbility.com/kr/employment/talent_02', '{"kind":"official_career_page_pointer","homepage_url":"https://www.doosanenerbility.com/kr","link_label":"채용"}'::jsonb),
(18, '공식 채용 페이지', '화력 분야 채용 정보 확인', 'https://www.saramin.co.kr/zf_user/company-info/view-inner-recruit?csn=RHZsVTQ4cGZPWjVuZXJoOEptS095dz09', '{"kind":"official_career_page_pointer","homepage_url":"https://www.doowonhi.com","link_label":"채용공고"}'::jsonb),
(24, '공식 채용 페이지', '기타 분야 채용 정보 확인', 'https://samyangct.com/recruit', '{"kind":"official_career_page_pointer","homepage_url":"https://samyangct.com","link_label":"/recruit"}'::jsonb),
(35, '공식 채용 페이지', '항공유도 분야 채용 정보 확인', 'https://satreci.recruiter.co.kr/career/home', '{"kind":"official_career_page_pointer","homepage_url":"https://www.satreci.com","link_label":"인재채용"}'::jsonb),
(36, '공식 채용 페이지', '화력 분야 채용 정보 확인', 'https://www.ecng.co.kr/recruit', '{"kind":"official_career_page_pointer","homepage_url":"https://www.ecng.co.kr","link_label":"/recruit"}'::jsonb),
(37, '공식 채용 페이지', '통신전자 분야 채용 정보 확인', 'http://i3system.com/%ec%9d%b8%ec%9e%ac%ec%b1%84%ec%9a%a9/%ec%b1%84%ec%9a%a9%ec%a0%95%eb%b3%b4', '{"kind":"official_career_page_pointer","homepage_url":"https://www.i3system.com","link_label":"채용정보"}'::jsonb),
(39, '공식 채용 페이지', '항공 분야 채용 정보 확인', 'https://www.aviosystech.com/page/sub04-1.php', '{"kind":"official_career_page_pointer","homepage_url":"https://www.aviosystech.com","link_label":"Recruit"}'::jsonb),
(40, '공식 채용 페이지', '화생방 분야 채용 정보 확인', 'https://www.hk-global.com/ko/recruit/want.html', '{"kind":"official_career_page_pointer","homepage_url":"https://www.hk-global.com","link_label":"채용정보"}'::jsonb),
(46, '공식 채용 페이지', '기타 분야 채용 정보 확인', 'https://www.silstar.co.kr/recruit', '{"kind":"official_career_page_pointer","homepage_url":"https://www.silstar.co.kr","link_label":"/recruit"}'::jsonb),
(47, '공식 채용 페이지', '통신전자 분야 채용 정보 확인', 'https://curiox.co.kr/sub/careers/recruitment.asp', '{"kind":"official_career_page_pointer","homepage_url":"https://curiox.co.kr","link_label":"인재채용"}'::jsonb),
(50, '공식 채용 페이지', '항공유도 분야 채용 정보 확인', 'https://www.spacepro.co.kr/bbs/board.php?bo_table=careers', '{"kind":"official_career_page_pointer","homepage_url":"https://www.spacepro.co.kr","link_label":"채용공고"}'::jsonb),
(53, '공식 채용 페이지', '항공유도 분야 채용 정보 확인', 'https://www.kaes.biz/recruit', '{"kind":"official_career_page_pointer","homepage_url":"https://www.kaes.biz","link_label":"/recruit"}'::jsonb),
(57, '공식 채용 페이지', '항공유도 분야 채용 정보 확인', 'https://www.firsteccom.co.kr/recruit/recruit_01', '{"kind":"official_career_page_pointer","homepage_url":"https://www.firsteccom.co.kr","link_label":"인재채용"}'::jsonb),
(59, '공식 채용 페이지', '탄약 분야 채용 정보 확인', 'https://www.poongsan.co.kr/recruit/disclosure/information', '{"kind":"official_career_page_pointer","homepage_url":"https://www.poongsan.co.kr","link_label":"채용정보"}'::jsonb),
(60, '공식 채용 페이지', '탄약 분야 채용 정보 확인', 'https://www.poongsanfns.co.kr/career', '{"kind":"official_career_page_pointer","homepage_url":"https://www.poongsanfns.co.kr","link_label":"채용정보"}'::jsonb),
(62, '공식 채용 페이지', '항공유도 분야 채용 정보 확인', 'https://www.koreaaero.com/recruit', '{"kind":"official_career_page_pointer","homepage_url":"https://www.koreaaero.com","link_label":"/recruit"}'::jsonb),
(65, '공식 채용 페이지', '함정 분야 채용 정보 확인', 'https://www.hanwhaocean.com/careers/ri', '{"kind":"official_career_page_pointer","homepage_url":"https://www.hanwhaocean.com/pub/main/index.do","link_label":"채용안내"}'::jsonb),
(67, '공식 채용 페이지', '항공유도 분야 채용 정보 확인', 'https://www.hanwhaaerospace.com/kor/careers/recruit.do', '{"kind":"official_career_page_pointer","homepage_url":"https://www.hanwhaaerospace.com","link_label":"채용안내"}'::jsonb),
(69, '공식 채용 페이지', '화력 분야 채용 정보 확인', 'https://www.hyundai-wia.com/recruit', '{"kind":"official_career_page_pointer","homepage_url":"https://www.hyundai-wia.com","link_label":"/recruit"}'::jsonb),
(71, '공식 채용 페이지', '기동 분야 채용 정보 확인', 'https://www.hyundai-transys.com/ko/careers/jobs.do', '{"kind":"official_career_page_pointer","homepage_url":"https://www.hyundai-transys.com","link_label":"인재채용"}'::jsonb),
(73, '공식 채용 페이지', '함정 분야 채용 정보 확인', 'https://www.hyosungheavyindustries.com/kr/company/recruitment/ideal-talent', '{"kind":"official_career_page_pointer","homepage_url":"https://www.hyosungheavyindustries.com","link_label":"인재채용"}'::jsonb),
(74, '공식 채용 페이지', '통신전자 분야 채용 정보 확인', 'https://www.huneed.com/%EC%B1%84%EC%9A%A9%EA%B3%B5%EA%B3%A0', '{"kind":"official_career_page_pointer","homepage_url":"https://www.huneed.com","link_label":"채용공고"}'::jsonb),
(77, '공식 채용 페이지', '함정 분야 채용 정보 확인', 'https://www.hjlite.com/recruit', '{"kind":"official_career_page_pointer","homepage_url":"https://www.hjlite.com","link_label":"/recruit"}'::jsonb),
(78, '공식 채용 페이지', '항공유도 분야 채용 정보 확인', 'https://www.ligcorp.com/recruit', '{"kind":"official_career_page_pointer","homepage_url":"https://www.ligcorp.com","link_label":"/recruit"}'::jsonb),
(85, '공식 채용 페이지', '기동 분야 채용 정보 확인', 'https://www.stxengine.co.kr/kor/html/recruit/talent.aspx', '{"kind":"official_career_page_pointer","homepage_url":"https://www.stxengine.co.kr","link_label":"채용정보"}'::jsonb)
)
insert into public.job_postings (
  company_id, source_id, title, job_function, employment_type, experience_level,
  preferred_military_experience, required_skills, preferred_skills, location,
  posting_url, is_active, raw
)
select
  rows.company_id,
  sources.id,
  rows.title,
  rows.job_function,
  null,
  null,
  '군 경력 및 방산 직무 연관 경험 우대 가능',
  '{}'::text[],
  '{}'::text[],
  null,
  rows.posting_url,
  null,
  rows.raw
from rows
join public.company_sources sources
  on sources.company_id = rows.company_id
 and sources.source_type = 'official_homepage_career_link'
 and sources.source_url = rows.posting_url
where not exists (
  select 1 from public.job_postings existing
  where existing.company_id = rows.company_id
    and existing.posting_url = rows.posting_url
    and existing.title = rows.title
);


commit;
