-- Generated from OpenDART empSttus.json and fnlttSinglAcnt.json.
-- Source docs:
-- - https://opendart.fss.or.kr/guide/detail.do?apiGrpCd=DS002&apiId=2019011
-- - https://opendart.fss.or.kr/guide/detail.do?apiGrpCd=DS003&apiId=2019016
-- Target year: 2021, report code: 11011

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    3,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2021',
    '광림 2021 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00103635&bsns_year=2021&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00103635","stock_code":"014200","target_year":"2021","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  3, 2021, 188434983966, 11277961364, -23012093089,
  164, 4577, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 3
    and existing.fiscal_year = 2021
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  3, '광림', '014200', '00103635',
  164, 2021, 4577, 2021, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 4577,
    salary_source = 'OpenDART 2021 사업보고서 직원 현황'
where id = 3
  and 4577 is not null;
-- raw: {"employee":{"employee_count":164,"avg_salary":4577},"financial":{"revenue":188434983966,"operating_profit":11277961364,"net_income":-23012093089}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    4,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2021',
    '기아 2021 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00106641&bsns_year=2021&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00106641","stock_code":"000270","target_year":"2021","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  4, 2021, 69862366000000, 5065685000000, 4760311000000,
  35501, 10200, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 4
    and existing.fiscal_year = 2021
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  4, '기아', '000270', '00106641',
  35501, 2021, 10200, 2021, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 10200,
    salary_source = 'OpenDART 2021 사업보고서 직원 현황'
where id = 4
  and 10200 is not null;
-- raw: {"employee":{"employee_count":35501,"avg_salary":10200},"financial":{"revenue":69862366000000,"operating_profit":5065685000000,"net_income":4760311000000}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    10,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2021',
    '대양전기공업 2021 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00111193&bsns_year=2021&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00111193","stock_code":"108380","target_year":"2021","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  10, 2021, 136604762213, 7259306665, 8836987665,
  364, 6100, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 10
    and existing.fiscal_year = 2021
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  10, '대양전기공업', '108380', '00111193',
  364, 2021, 6100, 2021, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 6100,
    salary_source = 'OpenDART 2021 사업보고서 직원 현황'
where id = 10
  and 6100 is not null;
-- raw: {"employee":{"employee_count":364,"avg_salary":6100},"financial":{"revenue":136604762213,"operating_profit":7259306665,"net_income":8836987665}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    12,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2021',
    '대한항공 2021 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00113526&bsns_year=2021&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00113526","stock_code":"003490","target_year":"2021","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  12, 2021, 9016824640301, 1417968632826, 578782033232,
  17992, 9294, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 12
    and existing.fiscal_year = 2021
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  12, '대한항공', '003490', '00113526',
  17992, 2021, 9294, 2021, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 9294,
    salary_source = 'OpenDART 2021 사업보고서 직원 현황'
where id = 12
  and 9294 is not null;
-- raw: {"employee":{"employee_count":17992,"avg_salary":9294},"financial":{"revenue":9016824640301,"operating_profit":1417968632826,"net_income":578782033232}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    13,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2021',
    '덕산넵코어스 2021 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00960623&bsns_year=2021&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00960623","stock_code":"","target_year":"2021","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  13, 2021, 30660742558, 201954201, 983141881,
  151, 4900, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 13
    and existing.fiscal_year = 2021
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  13, '덕산넵코어스', null, '00960623',
  151, 2021, 4900, 2021, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 4900,
    salary_source = 'OpenDART 2021 사업보고서 직원 현황'
where id = 13
  and 4900 is not null;
-- raw: {"employee":{"employee_count":151,"avg_salary":4900},"financial":{"revenue":30660742558,"operating_profit":201954201,"net_income":983141881}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    17,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2021',
    '두산에너빌리티 2021 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00159616&bsns_year=2021&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00159616","stock_code":"034020","target_year":"2021","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  17, 2021, 11283610608993, 877882794101, 645821146630,
  5622, 6700, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 17
    and existing.fiscal_year = 2021
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  17, '두산에너빌리티', '034020', '00159616',
  5622, 2021, 6700, 2021, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 6700,
    salary_source = 'OpenDART 2021 사업보고서 직원 현황'
where id = 17
  and 6700 is not null;
-- raw: {"employee":{"employee_count":5622,"avg_salary":6700},"financial":{"revenue":11283610608993,"operating_profit":877882794101,"net_income":645821146630}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    18,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2021',
    '두원중공업 2021 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00119724&bsns_year=2021&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00119724","stock_code":"","target_year":"2021","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  18, 2021, 0, 0, 0,
  563, null, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 18
    and existing.fiscal_year = 2021
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  18, '두원중공업', null, '00119724',
  563, 2021, null, 2021, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = null,
    salary_source = 'OpenDART 2021 사업보고서 직원 현황'
where id = 18
  and null is not null;
-- raw: {"employee":{"employee_count":563,"avg_salary":null},"financial":{"revenue":0,"operating_profit":0,"net_income":0}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    22,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2021',
    '빅텍 2021 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00385363&bsns_year=2021&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00385363","stock_code":"065450","target_year":"2021","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  22, 2021, 102466113395, 7132930977, 5264507187,
  201, 5300, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 22
    and existing.fiscal_year = 2021
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  22, '빅텍', '065450', '00385363',
  201, 2021, 5300, 2021, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 5300,
    salary_source = 'OpenDART 2021 사업보고서 직원 현황'
where id = 22
  and 5300 is not null;
-- raw: {"employee":{"employee_count":201,"avg_salary":5300},"financial":{"revenue":102466113395,"operating_profit":7132930977,"net_income":5264507187}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    26,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2021',
    '삼영이엔씨 2021 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00288343&bsns_year=2021&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00288343","stock_code":"065570","target_year":"2021","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  26, 2021, 40113737849, 1140806517, 622281165,
  271, 4483, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 26
    and existing.fiscal_year = 2021
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  26, '삼영이엔씨', '065570', '00288343',
  271, 2021, 4483, 2021, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 4483,
    salary_source = 'OpenDART 2021 사업보고서 직원 현황'
where id = 26
  and 4483 is not null;
-- raw: {"employee":{"employee_count":271,"avg_salary":4483},"financial":{"revenue":40113737849,"operating_profit":1140806517,"net_income":622281165}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    32,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2021',
    '스페코 2021 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00136165&bsns_year=2021&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00136165","stock_code":"013810","target_year":"2021","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  32, 2021, 54346966645, 2805011555, 1800550565,
  68, 7634, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 32
    and existing.fiscal_year = 2021
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  32, '스페코', '013810', '00136165',
  68, 2021, 7634, 2021, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 7634,
    salary_source = 'OpenDART 2021 사업보고서 직원 현황'
where id = 32
  and 7634 is not null;
-- raw: {"employee":{"employee_count":68,"avg_salary":7634},"financial":{"revenue":54346966645,"operating_profit":2805011555,"net_income":1800550565}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    35,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2021',
    '쎄트렉아이 2021 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00449254&bsns_year=2021&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00449254","stock_code":"099320","target_year":"2021","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  35, 2021, 73449328696, 1269234022, -12646852205,
  312, 6600, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 35
    and existing.fiscal_year = 2021
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  35, '쎄트렉아이', '099320', '00449254',
  312, 2021, 6600, 2021, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 6600,
    salary_source = 'OpenDART 2021 사업보고서 직원 현황'
where id = 35
  and 6600 is not null;
-- raw: {"employee":{"employee_count":312,"avg_salary":6600},"financial":{"revenue":73449328696,"operating_profit":1269234022,"net_income":-12646852205}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    37,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2021',
    '아이쓰리시스템 2021 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00612489&bsns_year=2021&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00612489","stock_code":"214430","target_year":"2021","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  37, 2021, 79723131606, 1410841017, 3357324317,
  433, 4451, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 37
    and existing.fiscal_year = 2021
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  37, '아이쓰리시스템', '214430', '00612489',
  433, 2021, 4451, 2021, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 4451,
    salary_source = 'OpenDART 2021 사업보고서 직원 현황'
where id = 37
  and 4451 is not null;
-- raw: {"employee":{"employee_count":433,"avg_salary":4451},"financial":{"revenue":79723131606,"operating_profit":1410841017,"net_income":3357324317}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    40,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2021',
    '에이치케이 2021 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00235183&bsns_year=2021&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00235183","stock_code":"044780","target_year":"2021","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  40, 2021, 71783044048, 4357189514, 5467676775,
  114, 5600, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 40
    and existing.fiscal_year = 2021
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  40, '에이치케이', '044780', '00235183',
  114, 2021, 5600, 2021, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 5600,
    salary_source = 'OpenDART 2021 사업보고서 직원 현황'
where id = 40
  and 5600 is not null;
-- raw: {"employee":{"employee_count":114,"avg_salary":5600},"financial":{"revenue":71783044048,"operating_profit":4357189514,"net_income":5467676775}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    48,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2021',
    '이화전기공업 2021 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00145738&bsns_year=2021&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00145738","stock_code":"024810","target_year":"2021","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  48, 2021, 66789424731, -2981278370, 27675410476,
  167, 5200, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 48
    and existing.fiscal_year = 2021
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  48, '이화전기공업', '024810', '00145738',
  167, 2021, 5200, 2021, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 5200,
    salary_source = 'OpenDART 2021 사업보고서 직원 현황'
where id = 48
  and 5200 is not null;
-- raw: {"employee":{"employee_count":167,"avg_salary":5200},"financial":{"revenue":66789424731,"operating_profit":-2981278370,"net_income":27675410476}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    55,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2021',
    '코오롱 2021 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00152862&bsns_year=2021&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00152862","stock_code":"002020","target_year":"2021","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  55, 2021, 5410414957004, 332198227180, 156794701735,
  64, 11386, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 55
    and existing.fiscal_year = 2021
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  55, '코오롱', '002020', '00152862',
  64, 2021, 11386, 2021, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 11386,
    salary_source = 'OpenDART 2021 사업보고서 직원 현황'
where id = 55
  and 11386 is not null;
-- raw: {"employee":{"employee_count":64,"avg_salary":11386},"financial":{"revenue":5410414957004,"operating_profit":332198227180,"net_income":156794701735}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    57,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2021',
    '퍼스텍 2021 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00148522&bsns_year=2021&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00148522","stock_code":"010820","target_year":"2021","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  57, 2021, 136697477681, 4334722379, 3874217894,
  356, 5200, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 57
    and existing.fiscal_year = 2021
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  57, '퍼스텍', '010820', '00148522',
  356, 2021, 5200, 2021, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 5200,
    salary_source = 'OpenDART 2021 사업보고서 직원 현황'
where id = 57
  and 5200 is not null;
-- raw: {"employee":{"employee_count":356,"avg_salary":5200},"financial":{"revenue":136697477681,"operating_profit":4334722379,"net_income":3874217894}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    58,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2021',
    '평화산업 2021 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00573579&bsns_year=2021&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00573579","stock_code":"090080","target_year":"2021","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  58, 2021, 424123466253, 5916278187, 205128216,
  806, 4800, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 58
    and existing.fiscal_year = 2021
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  58, '평화산업', '090080', '00573579',
  806, 2021, 4800, 2021, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 4800,
    salary_source = 'OpenDART 2021 사업보고서 직원 현황'
where id = 58
  and 4800 is not null;
-- raw: {"employee":{"employee_count":806,"avg_salary":4800},"financial":{"revenue":424123466253,"operating_profit":5916278187,"net_income":205128216}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    59,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2021',
    '풍산 2021 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00684714&bsns_year=2021&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00684714","stock_code":"103140","target_year":"2021","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  59, 2021, 3509498278523, 314125035707, 243387043769,
  3378, 8093, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 59
    and existing.fiscal_year = 2021
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  59, '풍산', '103140', '00684714',
  3378, 2021, 8093, 2021, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 8093,
    salary_source = 'OpenDART 2021 사업보고서 직원 현황'
where id = 59
  and 8093 is not null;
-- raw: {"employee":{"employee_count":3378,"avg_salary":8093},"financial":{"revenue":3509498278523,"operating_profit":314125035707,"net_income":243387043769}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    62,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2021',
    '한국항공우주 2021 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00309503&bsns_year=2021&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00309503","stock_code":"047810","target_year":"2021","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  62, 2021, 2562283675152, 58259436460, 53272528569,
  5012, 9300, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 62
    and existing.fiscal_year = 2021
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  62, '한국항공우주', '047810', '00309503',
  5012, 2021, 9300, 2021, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 9300,
    salary_source = 'OpenDART 2021 사업보고서 직원 현황'
where id = 62
  and 9300 is not null;
-- raw: {"employee":{"employee_count":5012,"avg_salary":9300},"financial":{"revenue":2562283675152,"operating_profit":58259436460,"net_income":53272528569}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    63,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2021',
    '한일단조 2021 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00162832&bsns_year=2021&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00162832","stock_code":"024740","target_year":"2021","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  63, 2021, 152471478934, -3353121692, -8675809923,
  141, 5479, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 63
    and existing.fiscal_year = 2021
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  63, '한일단조', '024740', '00162832',
  141, 2021, 5479, 2021, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 5479,
    salary_source = 'OpenDART 2021 사업보고서 직원 현황'
where id = 63
  and 5479 is not null;
-- raw: {"employee":{"employee_count":141,"avg_salary":5479},"financial":{"revenue":152471478934,"operating_profit":-3353121692,"net_income":-8675809923}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    64,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2021',
    '한컴라이프케어 2021 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00534598&bsns_year=2021&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00534598","stock_code":"372910","target_year":"2021","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  64, 2021, 121140356659, 4787002473, 4835069260,
  252, 6000, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 64
    and existing.fiscal_year = 2021
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  64, '한컴라이프케어', '372910', '00534598',
  252, 2021, 6000, 2021, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 6000,
    salary_source = 'OpenDART 2021 사업보고서 직원 현황'
where id = 64
  and 6000 is not null;
-- raw: {"employee":{"employee_count":252,"avg_salary":6000},"financial":{"revenue":121140356659,"operating_profit":4787002473,"net_income":4835069260}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    65,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2021',
    '한화오션 2021 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00111704&bsns_year=2021&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00111704","stock_code":"042660","target_year":"2021","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  65, 2021, 4486585681366, -1754651375507, -1699829429734,
  8802, 6800, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 65
    and existing.fiscal_year = 2021
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  65, '한화오션', '042660', '00111704',
  8802, 2021, 6800, 2021, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 6800,
    salary_source = 'OpenDART 2021 사업보고서 직원 현황'
where id = 65
  and 6800 is not null;
-- raw: {"employee":{"employee_count":8802,"avg_salary":6800},"financial":{"revenue":4486585681366,"operating_profit":-1754651375507,"net_income":-1699829429734}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    66,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2021',
    '한화시스템 2021 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00339391&bsns_year=2021&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00339391","stock_code":"272210","target_year":"2021","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  66, 2021, 2089503039125, 112049712222, 97878482869,
  3938, 8700, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 66
    and existing.fiscal_year = 2021
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  66, '한화시스템', '272210', '00339391',
  3938, 2021, 8700, 2021, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 8700,
    salary_source = 'OpenDART 2021 사업보고서 직원 현황'
where id = 66
  and 8700 is not null;
-- raw: {"employee":{"employee_count":3938,"avg_salary":8700},"financial":{"revenue":2089503039125,"operating_profit":112049712222,"net_income":97878482869}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    67,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2021',
    '한화에어로스페이스 2021 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00126566&bsns_year=2021&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00126566","stock_code":"012450","target_year":"2021","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  67, 2021, 6415087932347, 383046885903, 301762016281,
  1953, 8100, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 67
    and existing.fiscal_year = 2021
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  67, '한화에어로스페이스', '012450', '00126566',
  1953, 2021, 8100, 2021, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 8100,
    salary_source = 'OpenDART 2021 사업보고서 직원 현황'
where id = 67
  and 8100 is not null;
-- raw: {"employee":{"employee_count":1953,"avg_salary":8100},"financial":{"revenue":6415087932347,"operating_profit":383046885903,"net_income":301762016281}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    68,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2021',
    '현대로템 2021 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00302926&bsns_year=2021&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00302926","stock_code":"064350","target_year":"2021","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  68, 2021, 2872511952000, 80217965000, 51411601000,
  3444, 9300, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 68
    and existing.fiscal_year = 2021
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  68, '현대로템', '064350', '00302926',
  3444, 2021, 9300, 2021, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 9300,
    salary_source = 'OpenDART 2021 사업보고서 직원 현황'
where id = 68
  and 9300 is not null;
-- raw: {"employee":{"employee_count":3444,"avg_salary":9300},"financial":{"revenue":2872511952000,"operating_profit":80217965000,"net_income":51411601000}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    69,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2021',
    '현대위아 2021 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00106623&bsns_year=2021&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00106623","stock_code":"011210","target_year":"2021","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  69, 2021, 7527739000000, 102725000000, 56071000000,
  2902, 9600, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 69
    and existing.fiscal_year = 2021
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  69, '현대위아', '011210', '00106623',
  2902, 2021, 9600, 2021, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 9600,
    salary_source = 'OpenDART 2021 사업보고서 직원 현황'
where id = 69
  and 9600 is not null;
-- raw: {"employee":{"employee_count":2902,"avg_salary":9600},"financial":{"revenue":7527739000000,"operating_profit":102725000000,"net_income":56071000000}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    71,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2021',
    '현대트랜시스 2021 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00302634&bsns_year=2021&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00302634","stock_code":"","target_year":"2021","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  71, 2021, 0, 0, 0,
  3838, 8200, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 71
    and existing.fiscal_year = 2021
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  71, '현대트랜시스', null, '00302634',
  3838, 2021, 8200, 2021, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 8200,
    salary_source = 'OpenDART 2021 사업보고서 직원 현황'
where id = 71
  and 8200 is not null;
-- raw: {"employee":{"employee_count":3838,"avg_salary":8200},"financial":{"revenue":0,"operating_profit":0,"net_income":0}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    73,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2021',
    '효성중공업 2021 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=01316245&bsns_year=2021&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"01316245","stock_code":"298040","target_year":"2021","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  73, 2021, 3094698644786, 120066031213, 76516679128,
  3125, 7200, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 73
    and existing.fiscal_year = 2021
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  73, '효성중공업', '298040', '01316245',
  3125, 2021, 7200, 2021, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 7200,
    salary_source = 'OpenDART 2021 사업보고서 직원 현황'
where id = 73
  and 7200 is not null;
-- raw: {"employee":{"employee_count":3125,"avg_salary":7200},"financial":{"revenue":3094698644786,"operating_profit":120066031213,"net_income":76516679128}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    74,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2021',
    '휴니드테크놀러지스 2021 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00111421&bsns_year=2021&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00111421","stock_code":"005870","target_year":"2021","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  74, 2021, 227701907939, 13294091773, 13016423829,
  372, 5641, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 74
    and existing.fiscal_year = 2021
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  74, '휴니드테크놀러지스', '005870', '00111421',
  372, 2021, 5641, 2021, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 5641,
    salary_source = 'OpenDART 2021 사업보고서 직원 현황'
where id = 74
  and 5641 is not null;
-- raw: {"employee":{"employee_count":372,"avg_salary":5641},"financial":{"revenue":227701907939,"operating_profit":13294091773,"net_income":13016423829}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    75,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2021',
    'HD현대 2021 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=01205709&bsns_year=2021&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"01205709","stock_code":"267250","target_year":"2021","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  75, 2021, 28158746399000, 1085411576000, 186012264000,
  52, 13437, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 75
    and existing.fiscal_year = 2021
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  75, 'HD현대', '267250', '01205709',
  52, 2021, 13437, 2021, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 13437,
    salary_source = 'OpenDART 2021 사업보고서 직원 현황'
where id = 75
  and 13437 is not null;
-- raw: {"employee":{"employee_count":52,"avg_salary":13437},"financial":{"revenue":28158746399000,"operating_profit":1085411576000,"net_income":186012264000}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    76,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2021',
    'HD현대중공업 2021 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=01390344&bsns_year=2021&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"01390344","stock_code":"329180","target_year":"2021","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  76, 2021, 8311275924000, -800262777000, -814227962000,
  12811, null, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 76
    and existing.fiscal_year = 2021
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  76, 'HD현대중공업', '329180', '01390344',
  12811, 2021, null, 2021, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = null,
    salary_source = 'OpenDART 2021 사업보고서 직원 현황'
where id = 76
  and null is not null;
-- raw: {"employee":{"employee_count":12811,"avg_salary":null},"financial":{"revenue":8311275924000,"operating_profit":-800262777000,"net_income":-814227962000}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    77,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2021',
    'HJ중공업 2021 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00633835&bsns_year=2021&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00633835","stock_code":"097230","target_year":"2021","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  77, 2021, 1706532000000, -108991000000, -139844000000,
  2035, 7931, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 77
    and existing.fiscal_year = 2021
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  77, 'HJ중공업', '097230', '00633835',
  2035, 2021, 7931, 2021, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 7931,
    salary_source = 'OpenDART 2021 사업보고서 직원 현황'
where id = 77
  and 7931 is not null;
-- raw: {"employee":{"employee_count":2035,"avg_salary":7931},"financial":{"revenue":1706532000000,"operating_profit":-108991000000,"net_income":-139844000000}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    78,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2021',
    'LIG디펜스앤에어로스페이스 2021 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00503668&bsns_year=2021&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00503668","stock_code":"079550","target_year":"2021","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  78, 2021, 1822194315440, 97201006836, 105055805629,
  3263, 9100, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 78
    and existing.fiscal_year = 2021
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  78, 'LIG디펜스앤에어로스페이스', '079550', '00503668',
  3263, 2021, 9100, 2021, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 9100,
    salary_source = 'OpenDART 2021 사업보고서 직원 현황'
where id = 78
  and 9100 is not null;
-- raw: {"employee":{"employee_count":3263,"avg_salary":9100},"financial":{"revenue":1822194315440,"operating_profit":97201006836,"net_income":105055805629}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    82,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2021',
    'SK오션플랜트 2021 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00480367&bsns_year=2021&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00480367","stock_code":"100090","target_year":"2021","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  82, 2021, 503060400073, 26431994695, -86811625287,
  371, 4848, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 82
    and existing.fiscal_year = 2021
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  82, 'SK오션플랜트', '100090', '00480367',
  371, 2021, 4848, 2021, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 4848,
    salary_source = 'OpenDART 2021 사업보고서 직원 현황'
where id = 82
  and 4848 is not null;
-- raw: {"employee":{"employee_count":371,"avg_salary":4848},"financial":{"revenue":503060400073,"operating_profit":26431994695,"net_income":-86811625287}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    83,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2021',
    'SNT모티브 2021 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00398792&bsns_year=2021&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00398792","stock_code":"064960","target_year":"2021","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  83, 2021, 941744683893, 91595252246, 80118858406,
  726, 7200, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 83
    and existing.fiscal_year = 2021
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  83, 'SNT모티브', '064960', '00398792',
  726, 2021, 7200, 2021, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 7200,
    salary_source = 'OpenDART 2021 사업보고서 직원 현황'
where id = 83
  and 7200 is not null;
-- raw: {"employee":{"employee_count":726,"avg_salary":7200},"financial":{"revenue":941744683893,"operating_profit":91595252246,"net_income":80118858406}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    84,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2021',
    'SNT다이내믹스 2021 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00134477&bsns_year=2021&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00134477","stock_code":"003570","target_year":"2021","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  84, 2021, 335954012592, 20587466954, 58998656478,
  583, 6333, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 84
    and existing.fiscal_year = 2021
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  84, 'SNT다이내믹스', '003570', '00134477',
  583, 2021, 6333, 2021, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 6333,
    salary_source = 'OpenDART 2021 사업보고서 직원 현황'
where id = 84
  and 6333 is not null;
-- raw: {"employee":{"employee_count":583,"avg_salary":6333},"financial":{"revenue":335954012592,"operating_profit":20587466954,"net_income":58998656478}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    85,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2021',
    'STX엔진 2021 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00480455&bsns_year=2021&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00480455","stock_code":"077970","target_year":"2021","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  85, 2021, 493455000000, 3644000000, 1005000000,
  874, 6200, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 85
    and existing.fiscal_year = 2021
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  85, 'STX엔진', '077970', '00480455',
  874, 2021, 6200, 2021, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 6200,
    salary_source = 'OpenDART 2021 사업보고서 직원 현황'
where id = 85
  and 6200 is not null;
-- raw: {"employee":{"employee_count":874,"avg_salary":6200},"financial":{"revenue":493455000000,"operating_profit":3644000000,"net_income":1005000000}}
