-- Generated from OpenDART empSttus.json and fnlttSinglAcnt.json.
-- Source docs:
-- - https://opendart.fss.or.kr/guide/detail.do?apiGrpCd=DS002&apiId=2019011
-- - https://opendart.fss.or.kr/guide/detail.do?apiGrpCd=DS003&apiId=2019016
-- Target year: 2023, report code: 11011

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    3,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2023',
    '광림 2023 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00103635&bsns_year=2023&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00103635","stock_code":"014200","target_year":"2023","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  3, 2023, 182141667058, 10407620783, 12304650219,
  144, 5281, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 3
    and existing.fiscal_year = 2023
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  3, '광림', '014200', '00103635',
  144, 2023, 5281, 2023, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 5281,
    salary_source = 'OpenDART 2023 사업보고서 직원 현황'
where id = 3
  and 5281 is not null;
-- raw: {"employee":{"employee_count":144,"avg_salary":5281},"financial":{"revenue":182141667058,"operating_profit":10407620783,"net_income":12304650219}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    4,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2023',
    '기아 2023 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00106641&bsns_year=2023&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00106641","stock_code":"000270","target_year":"2023","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  4, 2023, 99808420000000, 11607873000000, 8777817000000,
  35737, 12800, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 4
    and existing.fiscal_year = 2023
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  4, '기아', '000270', '00106641',
  35737, 2023, 12800, 2023, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 12800,
    salary_source = 'OpenDART 2023 사업보고서 직원 현황'
where id = 4
  and 12800 is not null;
-- raw: {"employee":{"employee_count":35737,"avg_salary":12800},"financial":{"revenue":99808420000000,"operating_profit":11607873000000,"net_income":8777817000000}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    10,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2023',
    '대양전기공업 2023 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00111193&bsns_year=2023&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00111193","stock_code":"108380","target_year":"2023","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  10, 2023, 154347176318, 3734425846, 8378787832,
  373, 6100, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 10
    and existing.fiscal_year = 2023
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  10, '대양전기공업', '108380', '00111193',
  373, 2023, 6100, 2023, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 6100,
    salary_source = 'OpenDART 2023 사업보고서 직원 현황'
where id = 10
  and 6100 is not null;
-- raw: {"employee":{"employee_count":373,"avg_salary":6100},"financial":{"revenue":154347176318,"operating_profit":3734425846,"net_income":8378787832}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    12,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2023',
    '대한항공 2023 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00113526&bsns_year=2023&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00113526","stock_code":"003490","target_year":"2023","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  12, 2023, 16111796106147, 1790089190805, 1129105735756,
  18001, 12769, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 12
    and existing.fiscal_year = 2023
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  12, '대한항공', '003490', '00113526',
  18001, 2023, 12769, 2023, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 12769,
    salary_source = 'OpenDART 2023 사업보고서 직원 현황'
where id = 12
  and 12769 is not null;
-- raw: {"employee":{"employee_count":18001,"avg_salary":12769},"financial":{"revenue":16111796106147,"operating_profit":1790089190805,"net_income":1129105735756}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    13,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2023',
    '덕산넵코어스 2023 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00960623&bsns_year=2023&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00960623","stock_code":"","target_year":"2023","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  13, 2023, 31400000392, -5831185454, -4601619878,
  170, 5044, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 13
    and existing.fiscal_year = 2023
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  13, '덕산넵코어스', null, '00960623',
  170, 2023, 5044, 2023, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 5044,
    salary_source = 'OpenDART 2023 사업보고서 직원 현황'
where id = 13
  and 5044 is not null;
-- raw: {"employee":{"employee_count":170,"avg_salary":5044},"financial":{"revenue":31400000392,"operating_profit":-5831185454,"net_income":-4601619878}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    17,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2023',
    '두산에너빌리티 2023 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00159616&bsns_year=2023&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00159616","stock_code":"034020","target_year":"2023","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  17, 2023, 17589887709510, 1467318338124, 517521903042,
  5965, 8200, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 17
    and existing.fiscal_year = 2023
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  17, '두산에너빌리티', '034020', '00159616',
  5965, 2023, 8200, 2023, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 8200,
    salary_source = 'OpenDART 2023 사업보고서 직원 현황'
where id = 17
  and 8200 is not null;
-- raw: {"employee":{"employee_count":5965,"avg_salary":8200},"financial":{"revenue":17589887709510,"operating_profit":1467318338124,"net_income":517521903042}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    18,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2023',
    '두원중공업 2023 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00119724&bsns_year=2023&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00119724","stock_code":"","target_year":"2023","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  18, 2023, 0, 0, 0,
  582, 8100, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 18
    and existing.fiscal_year = 2023
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  18, '두원중공업', null, '00119724',
  582, 2023, 8100, 2023, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 8100,
    salary_source = 'OpenDART 2023 사업보고서 직원 현황'
where id = 18
  and 8100 is not null;
-- raw: {"employee":{"employee_count":582,"avg_salary":8100},"financial":{"revenue":0,"operating_profit":0,"net_income":0}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    22,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2023',
    '빅텍 2023 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00385363&bsns_year=2023&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00385363","stock_code":"065450","target_year":"2023","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  22, 2023, 54928577801, -4338006419, -4189360606,
  207, 5500, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 22
    and existing.fiscal_year = 2023
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  22, '빅텍', '065450', '00385363',
  207, 2023, 5500, 2023, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 5500,
    salary_source = 'OpenDART 2023 사업보고서 직원 현황'
where id = 22
  and 5500 is not null;
-- raw: {"employee":{"employee_count":207,"avg_salary":5500},"financial":{"revenue":54928577801,"operating_profit":-4338006419,"net_income":-4189360606}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    26,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2023',
    '삼영이엔씨 2023 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00288343&bsns_year=2023&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00288343","stock_code":"065570","target_year":"2023","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  26, 2023, 33338252948, -6125614406, -16223274401,
  260, 4764, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 26
    and existing.fiscal_year = 2023
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  26, '삼영이엔씨', '065570', '00288343',
  260, 2023, 4764, 2023, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 4764,
    salary_source = 'OpenDART 2023 사업보고서 직원 현황'
where id = 26
  and 4764 is not null;
-- raw: {"employee":{"employee_count":260,"avg_salary":4764},"financial":{"revenue":33338252948,"operating_profit":-6125614406,"net_income":-16223274401}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    32,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2023',
    '스페코 2023 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00136165&bsns_year=2023&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00136165","stock_code":"013810","target_year":"2023","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  32, 2023, 22987862181, -4148483505, -2057200716,
  65, 6876, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 32
    and existing.fiscal_year = 2023
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  32, '스페코', '013810', '00136165',
  65, 2023, 6876, 2023, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 6876,
    salary_source = 'OpenDART 2023 사업보고서 직원 현황'
where id = 32
  and 6876 is not null;
-- raw: {"employee":{"employee_count":65,"avg_salary":6876},"financial":{"revenue":22987862181,"operating_profit":-4148483505,"net_income":-2057200716}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    35,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2023',
    '쎄트렉아이 2023 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00449254&bsns_year=2023&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00449254","stock_code":"099320","target_year":"2023","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  35, 2023, 125433494958, -4353750903, 41465966732,
  400, 7400, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 35
    and existing.fiscal_year = 2023
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  35, '쎄트렉아이', '099320', '00449254',
  400, 2023, 7400, 2023, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 7400,
    salary_source = 'OpenDART 2023 사업보고서 직원 현황'
where id = 35
  and 7400 is not null;
-- raw: {"employee":{"employee_count":400,"avg_salary":7400},"financial":{"revenue":125433494958,"operating_profit":-4353750903,"net_income":41465966732}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    37,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2023',
    '아이쓰리시스템 2023 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00612489&bsns_year=2023&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00612489","stock_code":"214430","target_year":"2023","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  37, 2023, 121539205459, 12204489179, 12561262924,
  482, 5593, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 37
    and existing.fiscal_year = 2023
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  37, '아이쓰리시스템', '214430', '00612489',
  482, 2023, 5593, 2023, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 5593,
    salary_source = 'OpenDART 2023 사업보고서 직원 현황'
where id = 37
  and 5593 is not null;
-- raw: {"employee":{"employee_count":482,"avg_salary":5593},"financial":{"revenue":121539205459,"operating_profit":12204489179,"net_income":12561262924}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    40,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2023',
    '에이치케이 2023 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00235183&bsns_year=2023&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00235183","stock_code":"044780","target_year":"2023","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  40, 2023, 66637115087, 841585044, 1897983026,
  115, 5300, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 40
    and existing.fiscal_year = 2023
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  40, '에이치케이', '044780', '00235183',
  115, 2023, 5300, 2023, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 5300,
    salary_source = 'OpenDART 2023 사업보고서 직원 현황'
where id = 40
  and 5300 is not null;
-- raw: {"employee":{"employee_count":115,"avg_salary":5300},"financial":{"revenue":66637115087,"operating_profit":841585044,"net_income":1897983026}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    47,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2023',
    '큐리옥스바이오시스템즈 2023 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=01498974&bsns_year=2023&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"01498974","stock_code":"445680","target_year":"2023","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  47, 2023, 6787910936, -10557074113, -10041722918,
  22, 11900, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 47
    and existing.fiscal_year = 2023
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  47, '큐리옥스바이오시스템즈', '445680', '01498974',
  22, 2023, 11900, 2023, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 11900,
    salary_source = 'OpenDART 2023 사업보고서 직원 현황'
where id = 47
  and 11900 is not null;
-- raw: {"employee":{"employee_count":22,"avg_salary":11900},"financial":{"revenue":6787910936,"operating_profit":-10557074113,"net_income":-10041722918}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    48,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2023',
    '이화전기공업 2023 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00145738&bsns_year=2023&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00145738","stock_code":"024810","target_year":"2023","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  48, 2023, 65163779554, 3459330691, -9456454067,
  169, 5400, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 48
    and existing.fiscal_year = 2023
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  48, '이화전기공업', '024810', '00145738',
  169, 2023, 5400, 2023, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 5400,
    salary_source = 'OpenDART 2023 사업보고서 직원 현황'
where id = 48
  and 5400 is not null;
-- raw: {"employee":{"employee_count":169,"avg_salary":5400},"financial":{"revenue":65163779554,"operating_profit":3459330691,"net_income":-9456454067}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    55,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2023',
    '코오롱 2023 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00152862&bsns_year=2023&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00152862","stock_code":"002020","target_year":"2023","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  55, 2023, 5894231282101, 102926776246, 15387285329,
  80, 10661, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 55
    and existing.fiscal_year = 2023
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  55, '코오롱', '002020', '00152862',
  80, 2023, 10661, 2023, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 10661,
    salary_source = 'OpenDART 2023 사업보고서 직원 현황'
where id = 55
  and 10661 is not null;
-- raw: {"employee":{"employee_count":80,"avg_salary":10661},"financial":{"revenue":5894231282101,"operating_profit":102926776246,"net_income":15387285329}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    57,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2023',
    '퍼스텍 2023 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00148522&bsns_year=2023&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00148522","stock_code":"010820","target_year":"2023","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  57, 2023, 173103350935, 2508074315, 4620136432,
  388, 7000, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 57
    and existing.fiscal_year = 2023
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  57, '퍼스텍', '010820', '00148522',
  388, 2023, 7000, 2023, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 7000,
    salary_source = 'OpenDART 2023 사업보고서 직원 현황'
where id = 57
  and 7000 is not null;
-- raw: {"employee":{"employee_count":388,"avg_salary":7000},"financial":{"revenue":173103350935,"operating_profit":2508074315,"net_income":4620136432}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    58,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2023',
    '평화산업 2023 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00573579&bsns_year=2023&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00573579","stock_code":"090080","target_year":"2023","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  58, 2023, 564038964404, 9937617006, 3632456925,
  786, 5300, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 58
    and existing.fiscal_year = 2023
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  58, '평화산업', '090080', '00573579',
  786, 2023, 5300, 2023, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 5300,
    salary_source = 'OpenDART 2023 사업보고서 직원 현황'
where id = 58
  and 5300 is not null;
-- raw: {"employee":{"employee_count":786,"avg_salary":5300},"financial":{"revenue":564038964404,"operating_profit":9937617006,"net_income":3632456925}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    59,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2023',
    '풍산 2023 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00684714&bsns_year=2023&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00684714","stock_code":"103140","target_year":"2023","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  59, 2023, 4125263947257, 228636480718, 156440326543,
  3469, 9228, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 59
    and existing.fiscal_year = 2023
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  59, '풍산', '103140', '00684714',
  3469, 2023, 9228, 2023, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 9228,
    salary_source = 'OpenDART 2023 사업보고서 직원 현황'
where id = 59
  and 9228 is not null;
-- raw: {"employee":{"employee_count":3469,"avg_salary":9228},"financial":{"revenue":4125263947257,"operating_profit":228636480718,"net_income":156440326543}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    62,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2023',
    '한국항공우주 2023 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00309503&bsns_year=2023&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00309503","stock_code":"047810","target_year":"2023","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  62, 2023, 3819344382446, 247510483155, 221401119895,
  5098, 11100, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 62
    and existing.fiscal_year = 2023
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  62, '한국항공우주', '047810', '00309503',
  5098, 2023, 11100, 2023, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 11100,
    salary_source = 'OpenDART 2023 사업보고서 직원 현황'
where id = 62
  and 11100 is not null;
-- raw: {"employee":{"employee_count":5098,"avg_salary":11100},"financial":{"revenue":3819344382446,"operating_profit":247510483155,"net_income":221401119895}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    63,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2023',
    '한일단조 2023 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00162832&bsns_year=2023&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00162832","stock_code":"024740","target_year":"2023","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  63, 2023, 178166776876, 15168146222, 7759017223,
  123, 5108, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 63
    and existing.fiscal_year = 2023
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  63, '한일단조', '024740', '00162832',
  123, 2023, 5108, 2023, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 5108,
    salary_source = 'OpenDART 2023 사업보고서 직원 현황'
where id = 63
  and 5108 is not null;
-- raw: {"employee":{"employee_count":123,"avg_salary":5108},"financial":{"revenue":178166776876,"operating_profit":15168146222,"net_income":7759017223}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    64,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2023',
    '한컴라이프케어 2023 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00534598&bsns_year=2023&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00534598","stock_code":"372910","target_year":"2023","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  64, 2023, 112779715327, 1832106411, 871118626,
  222, 5600, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 64
    and existing.fiscal_year = 2023
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  64, '한컴라이프케어', '372910', '00534598',
  222, 2023, 5600, 2023, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 5600,
    salary_source = 'OpenDART 2023 사업보고서 직원 현황'
where id = 64
  and 5600 is not null;
-- raw: {"employee":{"employee_count":222,"avg_salary":5600},"financial":{"revenue":112779715327,"operating_profit":1832106411,"net_income":871118626}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    65,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2023',
    '한화오션 2023 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00111704&bsns_year=2023&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00111704","stock_code":"042660","target_year":"2023","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  65, 2023, 7408312265643, -196498300366, 160043854483,
  8892, 8400, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 65
    and existing.fiscal_year = 2023
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  65, '한화오션', '042660', '00111704',
  8892, 2023, 8400, 2023, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 8400,
    salary_source = 'OpenDART 2023 사업보고서 직원 현황'
where id = 65
  and 8400 is not null;
-- raw: {"employee":{"employee_count":8892,"avg_salary":8400},"financial":{"revenue":7408312265643,"operating_profit":-196498300366,"net_income":160043854483}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    66,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2023',
    '한화시스템 2023 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00339391&bsns_year=2023&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00339391","stock_code":"272210","target_year":"2023","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  66, 2023, 2453079541922, 92870721114, 343083288939,
  4741, 9600, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 66
    and existing.fiscal_year = 2023
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  66, '한화시스템', '272210', '00339391',
  4741, 2023, 9600, 2023, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 9600,
    salary_source = 'OpenDART 2023 사업보고서 직원 현황'
where id = 66
  and 9600 is not null;
-- raw: {"employee":{"employee_count":4741,"avg_salary":9600},"financial":{"revenue":2453079541922,"operating_profit":92870721114,"net_income":343083288939}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    67,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2023',
    '한화에어로스페이스 2023 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00126566&bsns_year=2023&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00126566","stock_code":"012450","target_year":"2023","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  67, 2023, 9359005981309, 691114682400, 976918345793,
  6816, 9200, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 67
    and existing.fiscal_year = 2023
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  67, '한화에어로스페이스', '012450', '00126566',
  6816, 2023, 9200, 2023, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 9200,
    salary_source = 'OpenDART 2023 사업보고서 직원 현황'
where id = 67
  and 9200 is not null;
-- raw: {"employee":{"employee_count":6816,"avg_salary":9200},"financial":{"revenue":9359005981309,"operating_profit":691114682400,"net_income":976918345793}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    68,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2023',
    '현대로템 2023 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00302926&bsns_year=2023&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00302926","stock_code":"064350","target_year":"2023","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  68, 2023, 3587382453000, 210046594000, 156778978000,
  3938, 11100, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 68
    and existing.fiscal_year = 2023
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  68, '현대로템', '064350', '00302926',
  3938, 2023, 11100, 2023, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 11100,
    salary_source = 'OpenDART 2023 사업보고서 직원 현황'
where id = 68
  and 11100 is not null;
-- raw: {"employee":{"employee_count":3938,"avg_salary":11100},"financial":{"revenue":3587382453000,"operating_profit":210046594000,"net_income":156778978000}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    69,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2023',
    '현대위아 2023 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00106623&bsns_year=2023&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00106623","stock_code":"011210","target_year":"2023","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  69, 2023, 8590316000000, 229216000000, 52548000000,
  3018, 11600, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 69
    and existing.fiscal_year = 2023
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  69, '현대위아', '011210', '00106623',
  3018, 2023, 11600, 2023, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 11600,
    salary_source = 'OpenDART 2023 사업보고서 직원 현황'
where id = 69
  and 11600 is not null;
-- raw: {"employee":{"employee_count":3018,"avg_salary":11600},"financial":{"revenue":8590316000000,"operating_profit":229216000000,"net_income":52548000000}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    71,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2023',
    '현대트랜시스 2023 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00302634&bsns_year=2023&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00302634","stock_code":"","target_year":"2023","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  71, 2023, 11693980000000, 116988000000, 96745000000,
  3948, 11000, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 71
    and existing.fiscal_year = 2023
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  71, '현대트랜시스', null, '00302634',
  3948, 2023, 11000, 2023, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 11000,
    salary_source = 'OpenDART 2023 사업보고서 직원 현황'
where id = 71
  and 11000 is not null;
-- raw: {"employee":{"employee_count":3948,"avg_salary":11000},"financial":{"revenue":11693980000000,"operating_profit":116988000000,"net_income":96745000000}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    73,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2023',
    '효성중공업 2023 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=01316245&bsns_year=2023&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"01316245","stock_code":"298040","target_year":"2023","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  73, 2023, 4300571503251, 257836947601, 131922316419,
  3266, 8000, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 73
    and existing.fiscal_year = 2023
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  73, '효성중공업', '298040', '01316245',
  3266, 2023, 8000, 2023, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 8000,
    salary_source = 'OpenDART 2023 사업보고서 직원 현황'
where id = 73
  and 8000 is not null;
-- raw: {"employee":{"employee_count":3266,"avg_salary":8000},"financial":{"revenue":4300571503251,"operating_profit":257836947601,"net_income":131922316419}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    74,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2023',
    '휴니드테크놀러지스 2023 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00111421&bsns_year=2023&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00111421","stock_code":"005870","target_year":"2023","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  74, 2023, 228843875014, 17360970116, 17876181009,
  380, 6351, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 74
    and existing.fiscal_year = 2023
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  74, '휴니드테크놀러지스', '005870', '00111421',
  380, 2023, 6351, 2023, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 6351,
    salary_source = 'OpenDART 2023 사업보고서 직원 현황'
where id = 74
  and 6351 is not null;
-- raw: {"employee":{"employee_count":380,"avg_salary":6351},"financial":{"revenue":228843875014,"operating_profit":17360970116,"net_income":17876181009}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    75,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2023',
    'HD현대 2023 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=01205709&bsns_year=2023&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"01205709","stock_code":"267250","target_year":"2023","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  75, 2023, 61331302785000, 2031563587000, 785832206000,
  54, 15752, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 75
    and existing.fiscal_year = 2023
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  75, 'HD현대', '267250', '01205709',
  54, 2023, 15752, 2023, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 15752,
    salary_source = 'OpenDART 2023 사업보고서 직원 현황'
where id = 75
  and 15752 is not null;
-- raw: {"employee":{"employee_count":54,"avg_salary":15752},"financial":{"revenue":61331302785000,"operating_profit":2031563587000,"net_income":785832206000}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    76,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2023',
    'HD현대중공업 2023 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=01390344&bsns_year=2023&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"01390344","stock_code":"329180","target_year":"2023","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  76, 2023, 11963925991000, 178639965000, 24689214000,
  13277, null, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 76
    and existing.fiscal_year = 2023
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  76, 'HD현대중공업', '329180', '01390344',
  13277, 2023, null, 2023, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = null,
    salary_source = 'OpenDART 2023 사업보고서 직원 현황'
where id = 76
  and null is not null;
-- raw: {"employee":{"employee_count":13277,"avg_salary":null},"financial":{"revenue":11963925991000,"operating_profit":178639965000,"net_income":24689214000}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    77,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2023',
    'HJ중공업 2023 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00633835&bsns_year=2023&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00633835","stock_code":"097230","target_year":"2023","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  77, 2023, 2162073000000, -108787000000, -114319000000,
  2197, 7712, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 77
    and existing.fiscal_year = 2023
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  77, 'HJ중공업', '097230', '00633835',
  2197, 2023, 7712, 2023, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 7712,
    salary_source = 'OpenDART 2023 사업보고서 직원 현황'
where id = 77
  and 7712 is not null;
-- raw: {"employee":{"employee_count":2197,"avg_salary":7712},"financial":{"revenue":2162073000000,"operating_profit":-108787000000,"net_income":-114319000000}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    78,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2023',
    'LIG디펜스앤에어로스페이스 2023 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00503668&bsns_year=2023&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00503668","stock_code":"079550","target_year":"2023","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  78, 2023, 2308571092877, 186378438940, 174962143119,
  4277, 9400, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 78
    and existing.fiscal_year = 2023
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  78, 'LIG디펜스앤에어로스페이스', '079550', '00503668',
  4277, 2023, 9400, 2023, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 9400,
    salary_source = 'OpenDART 2023 사업보고서 직원 현황'
where id = 78
  and 9400 is not null;
-- raw: {"employee":{"employee_count":4277,"avg_salary":9400},"financial":{"revenue":2308571092877,"operating_profit":186378438940,"net_income":174962143119}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    82,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2023',
    'SK오션플랜트 2023 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00480367&bsns_year=2023&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00480367","stock_code":"100090","target_year":"2023","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  82, 2023, 925835675846, 75604296314, 57548769236,
  671, 5401, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 82
    and existing.fiscal_year = 2023
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  82, 'SK오션플랜트', '100090', '00480367',
  671, 2023, 5401, 2023, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 5401,
    salary_source = 'OpenDART 2023 사업보고서 직원 현황'
where id = 82
  and 5401 is not null;
-- raw: {"employee":{"employee_count":671,"avg_salary":5401},"financial":{"revenue":925835675846,"operating_profit":75604296314,"net_income":57548769236}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    83,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2023',
    'SNT모티브 2023 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00398792&bsns_year=2023&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00398792","stock_code":"064960","target_year":"2023","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  83, 2023, 1136280172201, 116628673833, 86980060241,
  683, 8300, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 83
    and existing.fiscal_year = 2023
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  83, 'SNT모티브', '064960', '00398792',
  683, 2023, 8300, 2023, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 8300,
    salary_source = 'OpenDART 2023 사업보고서 직원 현황'
where id = 83
  and 8300 is not null;
-- raw: {"employee":{"employee_count":683,"avg_salary":8300},"financial":{"revenue":1136280172201,"operating_profit":116628673833,"net_income":86980060241}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    84,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2023',
    'SNT다이내믹스 2023 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00134477&bsns_year=2023&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00134477","stock_code":"003570","target_year":"2023","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  84, 2023, 485954273334, 41595970398, 49529807111,
  501, 7268, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 84
    and existing.fiscal_year = 2023
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  84, 'SNT다이내믹스', '003570', '00134477',
  501, 2023, 7268, 2023, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 7268,
    salary_source = 'OpenDART 2023 사업보고서 직원 현황'
where id = 84
  and 7268 is not null;
-- raw: {"employee":{"employee_count":501,"avg_salary":7268},"financial":{"revenue":485954273334,"operating_profit":41595970398,"net_income":49529807111}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    85,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2023',
    'STX엔진 2023 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00480455&bsns_year=2023&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00480455","stock_code":"077970","target_year":"2023","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  85, 2023, 630377000000, 18868000000, 5685000000,
  907, 7300, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 85
    and existing.fiscal_year = 2023
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  85, 'STX엔진', '077970', '00480455',
  907, 2023, 7300, 2023, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 7300,
    salary_source = 'OpenDART 2023 사업보고서 직원 현황'
where id = 85
  and 7300 is not null;
-- raw: {"employee":{"employee_count":907,"avg_salary":7300},"financial":{"revenue":630377000000,"operating_profit":18868000000,"net_income":5685000000}}
