-- Generated from OpenDART empSttus.json and fnlttSinglAcnt.json.
-- Source docs:
-- - https://opendart.fss.or.kr/guide/detail.do?apiGrpCd=DS002&apiId=2019011
-- - https://opendart.fss.or.kr/guide/detail.do?apiGrpCd=DS003&apiId=2019016
-- Target year: 2022, report code: 11011

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    3,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2022',
    '광림 2022 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00103635&bsns_year=2022&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00103635","stock_code":"014200","target_year":"2022","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  3, 2022, 206957469626, 22030179467, -26780781810,
  168, 5303, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 3
    and existing.fiscal_year = 2022
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  3, '광림', '014200', '00103635',
  168, 2022, 5303, 2022, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 5303,
    salary_source = 'OpenDART 2022 사업보고서 직원 현황'
where id = 3
  and 5303 is not null;
-- raw: {"employee":{"employee_count":168,"avg_salary":5303},"financial":{"revenue":206957469626,"operating_profit":22030179467,"net_income":-26780781810}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    4,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2022',
    '기아 2022 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00106641&bsns_year=2022&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00106641","stock_code":"000270","target_year":"2022","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  4, 2022, 86559029000000, 7233120000000, 5408976000000,
  35847, 11300, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 4
    and existing.fiscal_year = 2022
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  4, '기아', '000270', '00106641',
  35847, 2022, 11300, 2022, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 11300,
    salary_source = 'OpenDART 2022 사업보고서 직원 현황'
where id = 4
  and 11300 is not null;
-- raw: {"employee":{"employee_count":35847,"avg_salary":11300},"financial":{"revenue":86559029000000,"operating_profit":7233120000000,"net_income":5408976000000}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    10,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2022',
    '대양전기공업 2022 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00111193&bsns_year=2022&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00111193","stock_code":"108380","target_year":"2022","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  10, 2022, 130396027254, -9885634582, -7496350570,
  373, 6100, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 10
    and existing.fiscal_year = 2022
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  10, '대양전기공업', '108380', '00111193',
  373, 2022, 6100, 2022, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 6100,
    salary_source = 'OpenDART 2022 사업보고서 직원 현황'
where id = 10
  and 6100 is not null;
-- raw: {"employee":{"employee_count":373,"avg_salary":6100},"financial":{"revenue":130396027254,"operating_profit":-9885634582,"net_income":-7496350570}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    12,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2022',
    '대한항공 2022 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00113526&bsns_year=2022&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00113526","stock_code":"003490","target_year":"2022","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  12, 2022, 14096094819146, 2830586753727, 1729502852463,
  17746, 11718, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 12
    and existing.fiscal_year = 2022
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  12, '대한항공', '003490', '00113526',
  17746, 2022, 11718, 2022, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 11718,
    salary_source = 'OpenDART 2022 사업보고서 직원 현황'
where id = 12
  and 11718 is not null;
-- raw: {"employee":{"employee_count":17746,"avg_salary":11718},"financial":{"revenue":14096094819146,"operating_profit":2830586753727,"net_income":1729502852463}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    13,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2022',
    '덕산넵코어스 2022 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00960623&bsns_year=2022&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00960623","stock_code":"","target_year":"2022","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  13, 2022, 35048174398, 1383524133, 1238616981,
  180, 5100, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 13
    and existing.fiscal_year = 2022
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  13, '덕산넵코어스', null, '00960623',
  180, 2022, 5100, 2022, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 5100,
    salary_source = 'OpenDART 2022 사업보고서 직원 현황'
where id = 13
  and 5100 is not null;
-- raw: {"employee":{"employee_count":180,"avg_salary":5100},"financial":{"revenue":35048174398,"operating_profit":1383524133,"net_income":1238616981}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    17,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2022',
    '두산에너빌리티 2022 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00159616&bsns_year=2022&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00159616","stock_code":"034020","target_year":"2022","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  17, 2022, 15421058082388, 1106120868237, -453149865549,
  5816, 7900, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 17
    and existing.fiscal_year = 2022
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  17, '두산에너빌리티', '034020', '00159616',
  5816, 2022, 7900, 2022, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 7900,
    salary_source = 'OpenDART 2022 사업보고서 직원 현황'
where id = 17
  and 7900 is not null;
-- raw: {"employee":{"employee_count":5816,"avg_salary":7900},"financial":{"revenue":15421058082388,"operating_profit":1106120868237,"net_income":-453149865549}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    18,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2022',
    '두원중공업 2022 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00119724&bsns_year=2022&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00119724","stock_code":"","target_year":"2022","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  18, 2022, 0, 0, 0,
  573, 7800, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 18
    and existing.fiscal_year = 2022
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  18, '두원중공업', null, '00119724',
  573, 2022, 7800, 2022, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 7800,
    salary_source = 'OpenDART 2022 사업보고서 직원 현황'
where id = 18
  and 7800 is not null;
-- raw: {"employee":{"employee_count":573,"avg_salary":7800},"financial":{"revenue":0,"operating_profit":0,"net_income":0}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    22,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2022',
    '빅텍 2022 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00385363&bsns_year=2022&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00385363","stock_code":"065450","target_year":"2022","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  22, 2022, 74374891497, 1652772174, -231659193,
  198, 5100, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 22
    and existing.fiscal_year = 2022
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  22, '빅텍', '065450', '00385363',
  198, 2022, 5100, 2022, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 5100,
    salary_source = 'OpenDART 2022 사업보고서 직원 현황'
where id = 22
  and 5100 is not null;
-- raw: {"employee":{"employee_count":198,"avg_salary":5100},"financial":{"revenue":74374891497,"operating_profit":1652772174,"net_income":-231659193}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    26,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2022',
    '삼영이엔씨 2022 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00288343&bsns_year=2022&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00288343","stock_code":"065570","target_year":"2022","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  26, 2022, 31901368198, -20145835588, -41768936559,
  277, 4400, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 26
    and existing.fiscal_year = 2022
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  26, '삼영이엔씨', '065570', '00288343',
  277, 2022, 4400, 2022, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 4400,
    salary_source = 'OpenDART 2022 사업보고서 직원 현황'
where id = 26
  and 4400 is not null;
-- raw: {"employee":{"employee_count":277,"avg_salary":4400},"financial":{"revenue":31901368198,"operating_profit":-20145835588,"net_income":-41768936559}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    32,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2022',
    '스페코 2022 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00136165&bsns_year=2022&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00136165","stock_code":"013810","target_year":"2022","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  32, 2022, 31079586548, -3766587275, 611187601,
  64, 7248, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 32
    and existing.fiscal_year = 2022
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  32, '스페코', '013810', '00136165',
  64, 2022, 7248, 2022, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 7248,
    salary_source = 'OpenDART 2022 사업보고서 직원 현황'
where id = 32
  and 7248 is not null;
-- raw: {"employee":{"employee_count":64,"avg_salary":7248},"financial":{"revenue":31079586548,"operating_profit":-3766587275,"net_income":611187601}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    35,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2022',
    '쎄트렉아이 2022 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00449254&bsns_year=2022&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00449254","stock_code":"099320","target_year":"2022","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  35, 2022, 91357563655, -7728225536, -2809411045,
  346, 7000, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 35
    and existing.fiscal_year = 2022
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  35, '쎄트렉아이', '099320', '00449254',
  346, 2022, 7000, 2022, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 7000,
    salary_source = 'OpenDART 2022 사업보고서 직원 현황'
where id = 35
  and 7000 is not null;
-- raw: {"employee":{"employee_count":346,"avg_salary":7000},"financial":{"revenue":91357563655,"operating_profit":-7728225536,"net_income":-2809411045}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    37,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2022',
    '아이쓰리시스템 2022 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00612489&bsns_year=2022&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00612489","stock_code":"214430","target_year":"2022","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  37, 2022, 83845591819, 5686971942, 6183187601,
  444, 4731, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 37
    and existing.fiscal_year = 2022
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  37, '아이쓰리시스템', '214430', '00612489',
  444, 2022, 4731, 2022, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 4731,
    salary_source = 'OpenDART 2022 사업보고서 직원 현황'
where id = 37
  and 4731 is not null;
-- raw: {"employee":{"employee_count":444,"avg_salary":4731},"financial":{"revenue":83845591819,"operating_profit":5686971942,"net_income":6183187601}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    40,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2022',
    '에이치케이 2022 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00235183&bsns_year=2022&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00235183","stock_code":"044780","target_year":"2022","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  40, 2022, 81378633384, 5810468081, 4273038938,
  124, 6000, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 40
    and existing.fiscal_year = 2022
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  40, '에이치케이', '044780', '00235183',
  124, 2022, 6000, 2022, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 6000,
    salary_source = 'OpenDART 2022 사업보고서 직원 현황'
where id = 40
  and 6000 is not null;
-- raw: {"employee":{"employee_count":124,"avg_salary":6000},"financial":{"revenue":81378633384,"operating_profit":5810468081,"net_income":4273038938}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    48,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2022',
    '이화전기공업 2022 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00145738&bsns_year=2022&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00145738","stock_code":"024810","target_year":"2022","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  48, 2022, 52488492352, -2875788553, -83353497417,
  166, 4800, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 48
    and existing.fiscal_year = 2022
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  48, '이화전기공업', '024810', '00145738',
  166, 2022, 4800, 2022, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 4800,
    salary_source = 'OpenDART 2022 사업보고서 직원 현황'
where id = 48
  and 4800 is not null;
-- raw: {"employee":{"employee_count":166,"avg_salary":4800},"financial":{"revenue":52488492352,"operating_profit":-2875788553,"net_income":-83353497417}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    55,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2022',
    '코오롱 2022 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00152862&bsns_year=2022&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00152862","stock_code":"002020","target_year":"2022","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  55, 2022, 5659922374692, 310967816142, 166893294228,
  69, 11151, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 55
    and existing.fiscal_year = 2022
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  55, '코오롱', '002020', '00152862',
  69, 2022, 11151, 2022, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 11151,
    salary_source = 'OpenDART 2022 사업보고서 직원 현황'
where id = 55
  and 11151 is not null;
-- raw: {"employee":{"employee_count":69,"avg_salary":11151},"financial":{"revenue":5659922374692,"operating_profit":310967816142,"net_income":166893294228}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    57,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2022',
    '퍼스텍 2022 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00148522&bsns_year=2022&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00148522","stock_code":"010820","target_year":"2022","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  57, 2022, 160154489954, 3112927906, 1794177256,
  370, 6500, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 57
    and existing.fiscal_year = 2022
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  57, '퍼스텍', '010820', '00148522',
  370, 2022, 6500, 2022, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 6500,
    salary_source = 'OpenDART 2022 사업보고서 직원 현황'
where id = 57
  and 6500 is not null;
-- raw: {"employee":{"employee_count":370,"avg_salary":6500},"financial":{"revenue":160154489954,"operating_profit":3112927906,"net_income":1794177256}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    58,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2022',
    '평화산업 2022 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00573579&bsns_year=2022&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00573579","stock_code":"090080","target_year":"2022","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  58, 2022, 519932246828, 5734166110, 6083364529,
  792, 4800, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 58
    and existing.fiscal_year = 2022
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  58, '평화산업', '090080', '00573579',
  792, 2022, 4800, 2022, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 4800,
    salary_source = 'OpenDART 2022 사업보고서 직원 현황'
where id = 58
  and 4800 is not null;
-- raw: {"employee":{"employee_count":792,"avg_salary":4800},"financial":{"revenue":519932246828,"operating_profit":5734166110,"net_income":6083364529}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    59,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2022',
    '풍산 2022 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00684714&bsns_year=2022&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00684714","stock_code":"103140","target_year":"2022","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  59, 2022, 4372982501228, 231619553412, 175261942564,
  3412, 8530, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 59
    and existing.fiscal_year = 2022
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  59, '풍산', '103140', '00684714',
  3412, 2022, 8530, 2022, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 8530,
    salary_source = 'OpenDART 2022 사업보고서 직원 현황'
where id = 59
  and 8530 is not null;
-- raw: {"employee":{"employee_count":3412,"avg_salary":8530},"financial":{"revenue":4372982501228,"operating_profit":231619553412,"net_income":175261942564}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    62,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2022',
    '한국항공우주 2022 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00309503&bsns_year=2022&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00309503","stock_code":"047810","target_year":"2022","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  62, 2022, 2786888282702, 141617667318, 115919395720,
  5079, 10100, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 62
    and existing.fiscal_year = 2022
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  62, '한국항공우주', '047810', '00309503',
  5079, 2022, 10100, 2022, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 10100,
    salary_source = 'OpenDART 2022 사업보고서 직원 현황'
where id = 62
  and 10100 is not null;
-- raw: {"employee":{"employee_count":5079,"avg_salary":10100},"financial":{"revenue":2786888282702,"operating_profit":141617667318,"net_income":115919395720}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    63,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2022',
    '한일단조 2022 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00162832&bsns_year=2022&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00162832","stock_code":"024740","target_year":"2022","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  63, 2022, 177364538405, 14579806106, 7213556464,
  130, 5722, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 63
    and existing.fiscal_year = 2022
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  63, '한일단조', '024740', '00162832',
  130, 2022, 5722, 2022, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 5722,
    salary_source = 'OpenDART 2022 사업보고서 직원 현황'
where id = 63
  and 5722 is not null;
-- raw: {"employee":{"employee_count":130,"avg_salary":5722},"financial":{"revenue":177364538405,"operating_profit":14579806106,"net_income":7213556464}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    64,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2022',
    '한컴라이프케어 2022 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00534598&bsns_year=2022&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00534598","stock_code":"372910","target_year":"2022","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  64, 2022, 100120112846, -1332071025, 9269405838,
  224, 5800, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 64
    and existing.fiscal_year = 2022
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  64, '한컴라이프케어', '372910', '00534598',
  224, 2022, 5800, 2022, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 5800,
    salary_source = 'OpenDART 2022 사업보고서 직원 현황'
where id = 64
  and 5800 is not null;
-- raw: {"employee":{"employee_count":224,"avg_salary":5800},"financial":{"revenue":100120112846,"operating_profit":-1332071025,"net_income":9269405838}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    65,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2022',
    '한화오션 2022 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00111704&bsns_year=2022&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00111704","stock_code":"042660","target_year":"2022","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  65, 2022, 4860150249534, -1613564533698, -1744778447657,
  8629, 7500, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 65
    and existing.fiscal_year = 2022
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  65, '한화오션', '042660', '00111704',
  8629, 2022, 7500, 2022, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 7500,
    salary_source = 'OpenDART 2022 사업보고서 직원 현황'
where id = 65
  and 7500 is not null;
-- raw: {"employee":{"employee_count":8629,"avg_salary":7500},"financial":{"revenue":4860150249534,"operating_profit":-1613564533698,"net_income":-1744778447657}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    66,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2022',
    '한화시스템 2022 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00339391&bsns_year=2022&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00339391","stock_code":"272210","target_year":"2022","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  66, 2022, 2188002345349, 24022201122, -80760193717,
  4307, 9200, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 66
    and existing.fiscal_year = 2022
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  66, '한화시스템', '272210', '00339391',
  4307, 2022, 9200, 2022, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 9200,
    salary_source = 'OpenDART 2022 사업보고서 직원 현황'
where id = 66
  and 9200 is not null;
-- raw: {"employee":{"employee_count":4307,"avg_salary":9200},"financial":{"revenue":2188002345349,"operating_profit":24022201122,"net_income":-80760193717}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    67,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2022',
    '한화에어로스페이스 2022 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00126566&bsns_year=2022&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00126566","stock_code":"012450","target_year":"2022","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  67, 2022, 6539605817572, 377215126599, 152027954710,
  3690, 9600, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 67
    and existing.fiscal_year = 2022
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  67, '한화에어로스페이스', '012450', '00126566',
  3690, 2022, 9600, 2022, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 9600,
    salary_source = 'OpenDART 2022 사업보고서 직원 현황'
where id = 67
  and 9600 is not null;
-- raw: {"employee":{"employee_count":3690,"avg_salary":9600},"financial":{"revenue":6539605817572,"operating_profit":377215126599,"net_income":152027954710}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    68,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2022',
    '현대로템 2022 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00302926&bsns_year=2022&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00302926","stock_code":"064350","target_year":"2022","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  68, 2022, 3163343615000, 147486669000, 194534253000,
  3591, 10100, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 68
    and existing.fiscal_year = 2022
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  68, '현대로템', '064350', '00302926',
  3591, 2022, 10100, 2022, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 10100,
    salary_source = 'OpenDART 2022 사업보고서 직원 현황'
where id = 68
  and 10100 is not null;
-- raw: {"employee":{"employee_count":3591,"avg_salary":10100},"financial":{"revenue":3163343615000,"operating_profit":147486669000,"net_income":194534253000}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    69,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2022',
    '현대위아 2022 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00106623&bsns_year=2022&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00106623","stock_code":"011210","target_year":"2022","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  69, 2022, 8207614000000, 212115000000, 43482000000,
  2917, 10200, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 69
    and existing.fiscal_year = 2022
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  69, '현대위아', '011210', '00106623',
  2917, 2022, 10200, 2022, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 10200,
    salary_source = 'OpenDART 2022 사업보고서 직원 현황'
where id = 69
  and 10200 is not null;
-- raw: {"employee":{"employee_count":2917,"avg_salary":10200},"financial":{"revenue":8207614000000,"operating_profit":212115000000,"net_income":43482000000}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    71,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2022',
    '현대트랜시스 2022 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00302634&bsns_year=2022&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00302634","stock_code":"","target_year":"2022","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  71, 2022, 0, 0, 0,
  3925, 10000, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 71
    and existing.fiscal_year = 2022
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  71, '현대트랜시스', null, '00302634',
  3925, 2022, 10000, 2022, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 10000,
    salary_source = 'OpenDART 2022 사업보고서 직원 현황'
where id = 71
  and 10000 is not null;
-- raw: {"employee":{"employee_count":3925,"avg_salary":10000},"financial":{"revenue":0,"operating_profit":0,"net_income":0}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    73,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2022',
    '효성중공업 2022 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=01316245&bsns_year=2022&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"01316245","stock_code":"298040","target_year":"2022","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  73, 2022, 3510143917637, 143248629974, 29129546895,
  3131, 7700, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 73
    and existing.fiscal_year = 2022
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  73, '효성중공업', '298040', '01316245',
  3131, 2022, 7700, 2022, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 7700,
    salary_source = 'OpenDART 2022 사업보고서 직원 현황'
where id = 73
  and 7700 is not null;
-- raw: {"employee":{"employee_count":3131,"avg_salary":7700},"financial":{"revenue":3510143917637,"operating_profit":143248629974,"net_income":29129546895}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    74,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2022',
    '휴니드테크놀러지스 2022 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00111421&bsns_year=2022&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00111421","stock_code":"005870","target_year":"2022","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  74, 2022, 222470897615, 12661325441, 9259054398,
  364, 6136, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 74
    and existing.fiscal_year = 2022
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  74, '휴니드테크놀러지스', '005870', '00111421',
  364, 2022, 6136, 2022, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 6136,
    salary_source = 'OpenDART 2022 사업보고서 직원 현황'
where id = 74
  and 6136 is not null;
-- raw: {"employee":{"employee_count":364,"avg_salary":6136},"financial":{"revenue":222470897615,"operating_profit":12661325441,"net_income":9259054398}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    75,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2022',
    'HD현대 2022 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=01205709&bsns_year=2022&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"01205709","stock_code":"267250","target_year":"2022","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  75, 2022, 60849668073000, 3387008264000, 2234955013000,
  54, 16431, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 75
    and existing.fiscal_year = 2022
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  75, 'HD현대', '267250', '01205709',
  54, 2022, 16431, 2022, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 16431,
    salary_source = 'OpenDART 2022 사업보고서 직원 현황'
where id = 75
  and 16431 is not null;
-- raw: {"employee":{"employee_count":54,"avg_salary":16431},"financial":{"revenue":60849668073000,"operating_profit":3387008264000,"net_income":2234955013000}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    76,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2022',
    'HD현대중공업 2022 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=01390344&bsns_year=2022&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"01390344","stock_code":"329180","target_year":"2022","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  76, 2022, 9045480488000, -289151153000, -352064622000,
  12765, null, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 76
    and existing.fiscal_year = 2022
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  76, 'HD현대중공업', '329180', '01390344',
  12765, 2022, null, 2022, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = null,
    salary_source = 'OpenDART 2022 사업보고서 직원 현황'
where id = 76
  and null is not null;
-- raw: {"employee":{"employee_count":12765,"avg_salary":null},"financial":{"revenue":9045480488000,"operating_profit":-289151153000,"net_income":-352064622000}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    77,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2022',
    'HJ중공업 2022 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00633835&bsns_year=2022&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00633835","stock_code":"097230","target_year":"2022","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  77, 2022, 1788163000000, 6625000000, -50160000000,
  2054, 7407, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 77
    and existing.fiscal_year = 2022
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  77, 'HJ중공업', '097230', '00633835',
  2054, 2022, 7407, 2022, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 7407,
    salary_source = 'OpenDART 2022 사업보고서 직원 현황'
where id = 77
  and 7407 is not null;
-- raw: {"employee":{"employee_count":2054,"avg_salary":7407},"financial":{"revenue":1788163000000,"operating_profit":6625000000,"net_income":-50160000000}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    78,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2022',
    'LIG디펜스앤에어로스페이스 2022 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00503668&bsns_year=2022&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00503668","stock_code":"079550","target_year":"2022","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  78, 2022, 2220751868438, 179111737872, 122939587371,
  3773, 8900, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 78
    and existing.fiscal_year = 2022
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  78, 'LIG디펜스앤에어로스페이스', '079550', '00503668',
  3773, 2022, 8900, 2022, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 8900,
    salary_source = 'OpenDART 2022 사업보고서 직원 현황'
where id = 78
  and 8900 is not null;
-- raw: {"employee":{"employee_count":3773,"avg_salary":8900},"financial":{"revenue":2220751868438,"operating_profit":179111737872,"net_income":122939587371}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    82,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2022',
    'SK오션플랜트 2022 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00480367&bsns_year=2022&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00480367","stock_code":"100090","target_year":"2022","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  82, 2022, 691830139228, 71940779701, 28013900233,
  523, 5135, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 82
    and existing.fiscal_year = 2022
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  82, 'SK오션플랜트', '100090', '00480367',
  523, 2022, 5135, 2022, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 5135,
    salary_source = 'OpenDART 2022 사업보고서 직원 현황'
where id = 82
  and 5135 is not null;
-- raw: {"employee":{"employee_count":523,"avg_salary":5135},"financial":{"revenue":691830139228,"operating_profit":71940779701,"net_income":28013900233}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    83,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2022',
    'SNT모티브 2022 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00398792&bsns_year=2022&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00398792","stock_code":"064960","target_year":"2022","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  83, 2022, 1044860611248, 111925067671, 87508434250,
  716, 7500, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 83
    and existing.fiscal_year = 2022
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  83, 'SNT모티브', '064960', '00398792',
  716, 2022, 7500, 2022, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 7500,
    salary_source = 'OpenDART 2022 사업보고서 직원 현황'
where id = 83
  and 7500 is not null;
-- raw: {"employee":{"employee_count":716,"avg_salary":7500},"financial":{"revenue":1044860611248,"operating_profit":111925067671,"net_income":87508434250}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    84,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2022',
    'SNT다이내믹스 2022 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00134477&bsns_year=2022&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00134477","stock_code":"003570","target_year":"2022","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  84, 2022, 408024698269, 25764818854, 23006448479,
  558, 6705, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 84
    and existing.fiscal_year = 2022
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  84, 'SNT다이내믹스', '003570', '00134477',
  558, 2022, 6705, 2022, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 6705,
    salary_source = 'OpenDART 2022 사업보고서 직원 현황'
where id = 84
  and 6705 is not null;
-- raw: {"employee":{"employee_count":558,"avg_salary":6705},"financial":{"revenue":408024698269,"operating_profit":25764818854,"net_income":23006448479}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    85,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2022',
    'STX엔진 2022 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00480455&bsns_year=2022&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00480455","stock_code":"077970","target_year":"2022","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  85, 2022, 544021000000, -8816000000, -26683000000,
  877, 6600, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 85
    and existing.fiscal_year = 2022
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  85, 'STX엔진', '077970', '00480455',
  877, 2022, 6600, 2022, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 6600,
    salary_source = 'OpenDART 2022 사업보고서 직원 현황'
where id = 85
  and 6600 is not null;
-- raw: {"employee":{"employee_count":877,"avg_salary":6600},"financial":{"revenue":544021000000,"operating_profit":-8816000000,"net_income":-26683000000}}
