-- Generated from OpenDART empSttus.json and fnlttSinglAcnt.json.
-- Source docs:
-- - https://opendart.fss.or.kr/guide/detail.do?apiGrpCd=DS002&apiId=2019011
-- - https://opendart.fss.or.kr/guide/detail.do?apiGrpCd=DS003&apiId=2019016
-- Target year: 2025, report code: 11011

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    3,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2025',
    '광림 2025 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00103635&bsns_year=2025&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00103635","stock_code":"014200","target_year":"2025","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  3, 2025, 77311049839, 1246695104, 5270946513,
  129, 3771, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 3
    and existing.fiscal_year = 2025
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  3, '광림', '014200', '00103635',
  129, 2025, 3771, 2025, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 3771,
    salary_source = 'OpenDART 2025 사업보고서 직원 현황'
where id = 3
  and 3771 is not null;
-- raw: {"employee":{"employee_count":129,"avg_salary":3771},"financial":{"revenue":77311049839,"operating_profit":1246695104,"net_income":5270946513}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    4,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2025',
    '기아 2025 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00106641&bsns_year=2025&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00106641","stock_code":"000270","target_year":"2025","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  4, 2025, 114140919000000, 9078148000000, 7554174000000,
  36566, 13500, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 4
    and existing.fiscal_year = 2025
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  4, '기아', '000270', '00106641',
  36566, 2025, 13500, 2025, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 13500,
    salary_source = 'OpenDART 2025 사업보고서 직원 현황'
where id = 4
  and 13500 is not null;
-- raw: {"employee":{"employee_count":36566,"avg_salary":13500},"financial":{"revenue":114140919000000,"operating_profit":9078148000000,"net_income":7554174000000}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    10,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2025',
    '대양전기공업 2025 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00111193&bsns_year=2025&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00111193","stock_code":"108380","target_year":"2025","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  10, 2025, 230094825180, 27060476082, 24789386379,
  396, 7100, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 10
    and existing.fiscal_year = 2025
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  10, '대양전기공업', '108380', '00111193',
  396, 2025, 7100, 2025, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 7100,
    salary_source = 'OpenDART 2025 사업보고서 직원 현황'
where id = 10
  and 7100 is not null;
-- raw: {"employee":{"employee_count":396,"avg_salary":7100},"financial":{"revenue":230094825180,"operating_profit":27060476082,"net_income":24789386379}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    12,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2025',
    '대한항공 2025 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00113526&bsns_year=2025&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00113526","stock_code":"003490","target_year":"2025","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  12, 2025, 25225542379502, 1113589428051, 647272880287,
  18318, 14900, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 12
    and existing.fiscal_year = 2025
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  12, '대한항공', '003490', '00113526',
  18318, 2025, 14900, 2025, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 14900,
    salary_source = 'OpenDART 2025 사업보고서 직원 현황'
where id = 12
  and 14900 is not null;
-- raw: {"employee":{"employee_count":18318,"avg_salary":14900},"financial":{"revenue":25225542379502,"operating_profit":1113589428051,"net_income":647272880287}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    13,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2025',
    '덕산넵코어스 2025 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00960623&bsns_year=2025&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00960623","stock_code":"","target_year":"2025","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  13, 2025, 48503887013, 4080014383, 3667873555,
  174, 5069, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 13
    and existing.fiscal_year = 2025
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  13, '덕산넵코어스', null, '00960623',
  174, 2025, 5069, 2025, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 5069,
    salary_source = 'OpenDART 2025 사업보고서 직원 현황'
where id = 13
  and 5069 is not null;
-- raw: {"employee":{"employee_count":174,"avg_salary":5069},"financial":{"revenue":48503887013,"operating_profit":4080014383,"net_income":3667873555}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    17,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2025',
    '두산에너빌리티 2025 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00159616&bsns_year=2025&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00159616","stock_code":"034020","target_year":"2025","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  17, 2025, 17057876000000, 762712000000, 205163000000,
  6233, 10400, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 17
    and existing.fiscal_year = 2025
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  17, '두산에너빌리티', '034020', '00159616',
  6233, 2025, 10400, 2025, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 10400,
    salary_source = 'OpenDART 2025 사업보고서 직원 현황'
where id = 17
  and 10400 is not null;
-- raw: {"employee":{"employee_count":6233,"avg_salary":10400},"financial":{"revenue":17057876000000,"operating_profit":762712000000,"net_income":205163000000}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    18,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2025',
    '두원중공업 2025 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00119724&bsns_year=2025&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00119724","stock_code":"","target_year":"2025","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  18, 2025, 0, 0, 0,
  617, 8000, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 18
    and existing.fiscal_year = 2025
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  18, '두원중공업', null, '00119724',
  617, 2025, 8000, 2025, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 8000,
    salary_source = 'OpenDART 2025 사업보고서 직원 현황'
where id = 18
  and 8000 is not null;
-- raw: {"employee":{"employee_count":617,"avg_salary":8000},"financial":{"revenue":0,"operating_profit":0,"net_income":0}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    22,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2025',
    '빅텍 2025 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00385363&bsns_year=2025&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00385363","stock_code":"065450","target_year":"2025","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  22, 2025, 82956728421, 4373560135, 4402203493,
  247, 6100, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 22
    and existing.fiscal_year = 2025
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  22, '빅텍', '065450', '00385363',
  247, 2025, 6100, 2025, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 6100,
    salary_source = 'OpenDART 2025 사업보고서 직원 현황'
where id = 22
  and 6100 is not null;
-- raw: {"employee":{"employee_count":247,"avg_salary":6100},"financial":{"revenue":82956728421,"operating_profit":4373560135,"net_income":4402203493}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    24,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2025',
    '삼양컴텍 2025 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00141583&bsns_year=2025&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00141583","stock_code":"484590","target_year":"2025","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  24, 2025, 154607270230, 26631015664, 22669606521,
  528, 5800, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 24
    and existing.fiscal_year = 2025
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  24, '삼양컴텍', '484590', '00141583',
  528, 2025, 5800, 2025, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 5800,
    salary_source = 'OpenDART 2025 사업보고서 직원 현황'
where id = 24
  and 5800 is not null;
-- raw: {"employee":{"employee_count":528,"avg_salary":5800},"financial":{"revenue":154607270230,"operating_profit":26631015664,"net_income":22669606521}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    26,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2025',
    '삼영이엔씨 2025 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00288343&bsns_year=2025&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00288343","stock_code":"065570","target_year":"2025","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  26, 2025, 33261463483, -194608893, 840102788,
  190, 4500, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 26
    and existing.fiscal_year = 2025
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  26, '삼영이엔씨', '065570', '00288343',
  190, 2025, 4500, 2025, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 4500,
    salary_source = 'OpenDART 2025 사업보고서 직원 현황'
where id = 26
  and 4500 is not null;
-- raw: {"employee":{"employee_count":190,"avg_salary":4500},"financial":{"revenue":33261463483,"operating_profit":-194608893,"net_income":840102788}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    32,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2025',
    '스페코 2025 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00136165&bsns_year=2025&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00136165","stock_code":"013810","target_year":"2025","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  32, 2025, 37964956719, -460595979, -308438591,
  52, 7732, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 32
    and existing.fiscal_year = 2025
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  32, '스페코', '013810', '00136165',
  52, 2025, 7732, 2025, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 7732,
    salary_source = 'OpenDART 2025 사업보고서 직원 현황'
where id = 32
  and 7732 is not null;
-- raw: {"employee":{"employee_count":52,"avg_salary":7732},"financial":{"revenue":37964956719,"operating_profit":-460595979,"net_income":-308438591}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    35,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2025',
    '쎄트렉아이 2025 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00449254&bsns_year=2025&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00449254","stock_code":"099320","target_year":"2025","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  35, 2025, 206916796302, 10179660644, 14085784411,
  513, 8400, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 35
    and existing.fiscal_year = 2025
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  35, '쎄트렉아이', '099320', '00449254',
  513, 2025, 8400, 2025, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 8400,
    salary_source = 'OpenDART 2025 사업보고서 직원 현황'
where id = 35
  and 8400 is not null;
-- raw: {"employee":{"employee_count":513,"avg_salary":8400},"financial":{"revenue":206916796302,"operating_profit":10179660644,"net_income":14085784411}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    37,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2025',
    '아이쓰리시스템 2025 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00612489&bsns_year=2025&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00612489","stock_code":"214430","target_year":"2025","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  37, 2025, 124275749815, 16458043794, 18783320910,
  507, 6782, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 37
    and existing.fiscal_year = 2025
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  37, '아이쓰리시스템', '214430', '00612489',
  507, 2025, 6782, 2025, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 6782,
    salary_source = 'OpenDART 2025 사업보고서 직원 현황'
where id = 37
  and 6782 is not null;
-- raw: {"employee":{"employee_count":507,"avg_salary":6782},"financial":{"revenue":124275749815,"operating_profit":16458043794,"net_income":18783320910}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    40,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2025',
    '에이치케이 2025 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00235183&bsns_year=2025&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00235183","stock_code":"044780","target_year":"2025","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  40, 2025, 54189734390, -387452903, 4572314524,
  106, 6000, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 40
    and existing.fiscal_year = 2025
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  40, '에이치케이', '044780', '00235183',
  106, 2025, 6000, 2025, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 6000,
    salary_source = 'OpenDART 2025 사업보고서 직원 현황'
where id = 40
  and 6000 is not null;
-- raw: {"employee":{"employee_count":106,"avg_salary":6000},"financial":{"revenue":54189734390,"operating_profit":-387452903,"net_income":4572314524}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    47,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2025',
    '큐리옥스바이오시스템즈 2025 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=01498974&bsns_year=2025&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"01498974","stock_code":"445680","target_year":"2025","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  47, 2025, 5151548437, -12314428922, -27177567437,
  22, 5200, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 47
    and existing.fiscal_year = 2025
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  47, '큐리옥스바이오시스템즈', '445680', '01498974',
  22, 2025, 5200, 2025, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 5200,
    salary_source = 'OpenDART 2025 사업보고서 직원 현황'
where id = 47
  and 5200 is not null;
-- raw: {"employee":{"employee_count":22,"avg_salary":5200},"financial":{"revenue":5151548437,"operating_profit":-12314428922,"net_income":-27177567437}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    48,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2025',
    '이화전기공업 2025 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00145738&bsns_year=2025&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00145738","stock_code":"024810","target_year":"2025","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  48, 2025, 60887261315, -2158246010, -1573826698,
  183, 5600, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 48
    and existing.fiscal_year = 2025
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  48, '이화전기공업', '024810', '00145738',
  183, 2025, 5600, 2025, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 5600,
    salary_source = 'OpenDART 2025 사업보고서 직원 현황'
where id = 48
  and 5600 is not null;
-- raw: {"employee":{"employee_count":183,"avg_salary":5600},"financial":{"revenue":60887261315,"operating_profit":-2158246010,"net_income":-1573826698}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    55,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2025',
    '코오롱 2025 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00152862&bsns_year=2025&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00152862","stock_code":"002020","target_year":"2025","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  55, 2025, 5886133083763, 60501208348, -296605779721,
  91, 11716, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 55
    and existing.fiscal_year = 2025
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  55, '코오롱', '002020', '00152862',
  91, 2025, 11716, 2025, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 11716,
    salary_source = 'OpenDART 2025 사업보고서 직원 현황'
where id = 55
  and 11716 is not null;
-- raw: {"employee":{"employee_count":91,"avg_salary":11716},"financial":{"revenue":5886133083763,"operating_profit":60501208348,"net_income":-296605779721}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    57,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2025',
    '퍼스텍 2025 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00148522&bsns_year=2025&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00148522","stock_code":"010820","target_year":"2025","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  57, 2025, 294842426804, 10663228873, 14726828528,
  439, 6000, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 57
    and existing.fiscal_year = 2025
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  57, '퍼스텍', '010820', '00148522',
  439, 2025, 6000, 2025, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 6000,
    salary_source = 'OpenDART 2025 사업보고서 직원 현황'
where id = 57
  and 6000 is not null;
-- raw: {"employee":{"employee_count":439,"avg_salary":6000},"financial":{"revenue":294842426804,"operating_profit":10663228873,"net_income":14726828528}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    58,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2025',
    '평화산업 2025 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00573579&bsns_year=2025&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00573579","stock_code":"090080","target_year":"2025","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  58, 2025, 626062341683, 13342639921, 15706368362,
  833, 5900, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 58
    and existing.fiscal_year = 2025
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  58, '평화산업', '090080', '00573579',
  833, 2025, 5900, 2025, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 5900,
    salary_source = 'OpenDART 2025 사업보고서 직원 현황'
where id = 58
  and 5900 is not null;
-- raw: {"employee":{"employee_count":833,"avg_salary":5900},"financial":{"revenue":626062341683,"operating_profit":13342639921,"net_income":15706368362}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    59,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2025',
    '풍산 2025 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00684714&bsns_year=2025&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00684714","stock_code":"103140","target_year":"2025","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  59, 2025, 5048580386639, 297427463130, 147164434318,
  3754, 9814, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 59
    and existing.fiscal_year = 2025
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  59, '풍산', '103140', '00684714',
  3754, 2025, 9814, 2025, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 9814,
    salary_source = 'OpenDART 2025 사업보고서 직원 현황'
where id = 59
  and 9814 is not null;
-- raw: {"employee":{"employee_count":3754,"avg_salary":9814},"financial":{"revenue":5048580386639,"operating_profit":297427463130,"net_income":147164434318}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    62,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2025',
    '한국항공우주 2025 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00309503&bsns_year=2025&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00309503","stock_code":"047810","target_year":"2025","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  62, 2025, 3696379351601, 269190196660, 187312615904,
  5241, 12300, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 62
    and existing.fiscal_year = 2025
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  62, '한국항공우주', '047810', '00309503',
  5241, 2025, 12300, 2025, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 12300,
    salary_source = 'OpenDART 2025 사업보고서 직원 현황'
where id = 62
  and 12300 is not null;
-- raw: {"employee":{"employee_count":5241,"avg_salary":12300},"financial":{"revenue":3696379351601,"operating_profit":269190196660,"net_income":187312615904}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    63,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2025',
    '한일단조 2025 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00162832&bsns_year=2025&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00162832","stock_code":"024740","target_year":"2025","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  63, 2025, 126595207214, 3519821207, 1866767149,
  138, 6144, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 63
    and existing.fiscal_year = 2025
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  63, '한일단조', '024740', '00162832',
  138, 2025, 6144, 2025, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 6144,
    salary_source = 'OpenDART 2025 사업보고서 직원 현황'
where id = 63
  and 6144 is not null;
-- raw: {"employee":{"employee_count":138,"avg_salary":6144},"financial":{"revenue":126595207214,"operating_profit":3519821207,"net_income":1866767149}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    64,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2025',
    '한컴라이프케어 2025 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00534598&bsns_year=2025&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00534598","stock_code":"372910","target_year":"2025","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  64, 2025, 92088469654, -727292956, -7665648499,
  215, 6100, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 64
    and existing.fiscal_year = 2025
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  64, '한컴라이프케어', '372910', '00534598',
  215, 2025, 6100, 2025, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 6100,
    salary_source = 'OpenDART 2025 사업보고서 직원 현황'
where id = 64
  and 6100 is not null;
-- raw: {"employee":{"employee_count":215,"avg_salary":6100},"financial":{"revenue":92088469654,"operating_profit":-727292956,"net_income":-7665648499}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    65,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2025',
    '한화오션 2025 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00111704&bsns_year=2025&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00111704","stock_code":"042660","target_year":"2025","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  65, 2025, 12783512278323, 1167590137928, 1245921538208,
  11178, 9900, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 65
    and existing.fiscal_year = 2025
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  65, '한화오션', '042660', '00111704',
  11178, 2025, 9900, 2025, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 9900,
    salary_source = 'OpenDART 2025 사업보고서 직원 현황'
where id = 65
  and 9900 is not null;
-- raw: {"employee":{"employee_count":11178,"avg_salary":9900},"financial":{"revenue":12783512278323,"operating_profit":1167590137928,"net_income":1245921538208}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    66,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2025',
    '한화시스템 2025 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00339391&bsns_year=2025&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00339391","stock_code":"272210","target_year":"2025","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  66, 2025, 3664150568020, 119898725355, 209145275418,
  4855, 11300, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 66
    and existing.fiscal_year = 2025
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  66, '한화시스템', '272210', '00339391',
  4855, 2025, 11300, 2025, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 11300,
    salary_source = 'OpenDART 2025 사업보고서 직원 현황'
where id = 66
  and 11300 is not null;
-- raw: {"employee":{"employee_count":4855,"avg_salary":11300},"financial":{"revenue":3664150568020,"operating_profit":119898725355,"net_income":209145275418}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    67,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2025',
    '한화에어로스페이스 2025 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00126566&bsns_year=2025&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00126566","stock_code":"012450","target_year":"2025","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  67, 2025, 26702901249000, 3089320181000, 2201983086000,
  8168, 13300, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 67
    and existing.fiscal_year = 2025
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  67, '한화에어로스페이스', '012450', '00126566',
  8168, 2025, 13300, 2025, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 13300,
    salary_source = 'OpenDART 2025 사업보고서 직원 현황'
where id = 67
  and 13300 is not null;
-- raw: {"employee":{"employee_count":8168,"avg_salary":13300},"financial":{"revenue":26702901249000,"operating_profit":3089320181000,"net_income":2201983086000}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    68,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2025',
    '현대로템 2025 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00302926&bsns_year=2025&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00302926","stock_code":"064350","target_year":"2025","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  68, 2025, 5839031553000, 1005640509000, 770492199000,
  4541, 12400, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 68
    and existing.fiscal_year = 2025
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  68, '현대로템', '064350', '00302926',
  4541, 2025, 12400, 2025, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 12400,
    salary_source = 'OpenDART 2025 사업보고서 직원 현황'
where id = 68
  and 12400 is not null;
-- raw: {"employee":{"employee_count":4541,"avg_salary":12400},"financial":{"revenue":5839031553000,"operating_profit":1005640509000,"net_income":770492199000}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    69,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2025',
    '현대위아 2025 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00106623&bsns_year=2025&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00106623","stock_code":"011210","target_year":"2025","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  69, 2025, 8481561000000, 204413000000, 116932000000,
  2843, 13200, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 69
    and existing.fiscal_year = 2025
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  69, '현대위아', '011210', '00106623',
  2843, 2025, 13200, 2025, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 13200,
    salary_source = 'OpenDART 2025 사업보고서 직원 현황'
where id = 69
  and 13200 is not null;
-- raw: {"employee":{"employee_count":2843,"avg_salary":13200},"financial":{"revenue":8481561000000,"operating_profit":204413000000,"net_income":116932000000}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    71,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2025',
    '현대트랜시스 2025 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00302634&bsns_year=2025&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00302634","stock_code":"","target_year":"2025","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  71, 2025, 14839047000000, 336042000000, 115284000000,
  4061, 11200, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 71
    and existing.fiscal_year = 2025
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  71, '현대트랜시스', null, '00302634',
  4061, 2025, 11200, 2025, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 11200,
    salary_source = 'OpenDART 2025 사업보고서 직원 현황'
where id = 71
  and 11200 is not null;
-- raw: {"employee":{"employee_count":4061,"avg_salary":11200},"financial":{"revenue":14839047000000,"operating_profit":336042000000,"net_income":115284000000}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    73,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2025',
    '효성중공업 2025 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=01316245&bsns_year=2025&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"01316245","stock_code":"298040","target_year":"2025","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  73, 2025, 5968511616609, 746968417289, 502837667965,
  3567, 9200, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 73
    and existing.fiscal_year = 2025
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  73, '효성중공업', '298040', '01316245',
  3567, 2025, 9200, 2025, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 9200,
    salary_source = 'OpenDART 2025 사업보고서 직원 현황'
where id = 73
  and 9200 is not null;
-- raw: {"employee":{"employee_count":3567,"avg_salary":9200},"financial":{"revenue":5968511616609,"operating_profit":746968417289,"net_income":502837667965}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    74,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2025',
    '휴니드테크놀러지스 2025 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00111421&bsns_year=2025&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00111421","stock_code":"005870","target_year":"2025","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  74, 2025, 137185901827, -12032815348, -9985113192,
  310, 7055, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 74
    and existing.fiscal_year = 2025
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  74, '휴니드테크놀러지스', '005870', '00111421',
  310, 2025, 7055, 2025, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 7055,
    salary_source = 'OpenDART 2025 사업보고서 직원 현황'
where id = 74
  and 7055 is not null;
-- raw: {"employee":{"employee_count":310,"avg_salary":7055},"financial":{"revenue":137185901827,"operating_profit":-12032815348,"net_income":-9985113192}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    75,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2025',
    'HD현대 2025 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=01205709&bsns_year=2025&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"01205709","stock_code":"267250","target_year":"2025","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  75, 2025, 71259438270000, 6099636253000, 3675482625000,
  48, 22625, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 75
    and existing.fiscal_year = 2025
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  75, 'HD현대', '267250', '01205709',
  48, 2025, 22625, 2025, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 22625,
    salary_source = 'OpenDART 2025 사업보고서 직원 현황'
where id = 75
  and 22625 is not null;
-- raw: {"employee":{"employee_count":48,"avg_salary":22625},"financial":{"revenue":71259438270000,"operating_profit":6099636253000,"net_income":3675482625000}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    76,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2025',
    'HD현대중공업 2025 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=01390344&bsns_year=2025&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"01390344","stock_code":"329180","target_year":"2025","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  76, 2025, 17580633257000, 2037510103000, 1415484565000,
  18880, null, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 76
    and existing.fiscal_year = 2025
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  76, 'HD현대중공업', '329180', '01390344',
  18880, 2025, null, 2025, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = null,
    salary_source = 'OpenDART 2025 사업보고서 직원 현황'
where id = 76
  and null is not null;
-- raw: {"employee":{"employee_count":18880,"avg_salary":null},"financial":{"revenue":17580633257000,"operating_profit":2037510103000,"net_income":1415484565000}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    77,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2025',
    'HJ중공업 2025 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00633835&bsns_year=2025&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00633835","stock_code":"097230","target_year":"2025","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  77, 2025, 1999705000000, 67074000000, 51444000000,
  2097, 7789, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 77
    and existing.fiscal_year = 2025
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  77, 'HJ중공업', '097230', '00633835',
  2097, 2025, 7789, 2025, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 7789,
    salary_source = 'OpenDART 2025 사업보고서 직원 현황'
where id = 77
  and 7789 is not null;
-- raw: {"employee":{"employee_count":2097,"avg_salary":7789},"financial":{"revenue":1999705000000,"operating_profit":67074000000,"net_income":51444000000}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    78,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2025',
    'LIG디펜스앤에어로스페이스 2025 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00503668&bsns_year=2025&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00503668","stock_code":"079550","target_year":"2025","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  78, 2025, 4306936127418, 319442306790, 237479536396,
  5382, 10900, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 78
    and existing.fiscal_year = 2025
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  78, 'LIG디펜스앤에어로스페이스', '079550', '00503668',
  5382, 2025, 10900, 2025, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 10900,
    salary_source = 'OpenDART 2025 사업보고서 직원 현황'
where id = 78
  and 10900 is not null;
-- raw: {"employee":{"employee_count":5382,"avg_salary":10900},"financial":{"revenue":4306936127418,"operating_profit":319442306790,"net_income":237479536396}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    82,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2025',
    'SK오션플랜트 2025 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00480367&bsns_year=2025&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00480367","stock_code":"100090","target_year":"2025","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  82, 2025, 965388430763, 59509493978, 37510843066,
  628, 7153, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 82
    and existing.fiscal_year = 2025
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  82, 'SK오션플랜트', '100090', '00480367',
  628, 2025, 7153, 2025, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 7153,
    salary_source = 'OpenDART 2025 사업보고서 직원 현황'
where id = 82
  and 7153 is not null;
-- raw: {"employee":{"employee_count":628,"avg_salary":7153},"financial":{"revenue":965388430763,"operating_profit":59509493978,"net_income":37510843066}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    83,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2025',
    'SNT모티브 2025 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00398792&bsns_year=2025&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00398792","stock_code":"064960","target_year":"2025","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  83, 2025, 1006373968570, 102552954912, 69508148662,
  536, 8900, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 83
    and existing.fiscal_year = 2025
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  83, 'SNT모티브', '064960', '00398792',
  536, 2025, 8900, 2025, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 8900,
    salary_source = 'OpenDART 2025 사업보고서 직원 현황'
where id = 83
  and 8900 is not null;
-- raw: {"employee":{"employee_count":536,"avg_salary":8900},"financial":{"revenue":1006373968570,"operating_profit":102552954912,"net_income":69508148662}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    84,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2025',
    'SNT다이내믹스 2025 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00134477&bsns_year=2025&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00134477","stock_code":"003570","target_year":"2025","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  84, 2025, 712021619474, 85457001419, 61574936460,
  381, 8445, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 84
    and existing.fiscal_year = 2025
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  84, 'SNT다이내믹스', '003570', '00134477',
  381, 2025, 8445, 2025, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 8445,
    salary_source = 'OpenDART 2025 사업보고서 직원 현황'
where id = 84
  and 8445 is not null;
-- raw: {"employee":{"employee_count":381,"avg_salary":8445},"financial":{"revenue":712021619474,"operating_profit":85457001419,"net_income":61574936460}}

with source_upsert as (
  insert into public.company_sources (
    company_id, source_grade, source_type, title, source_url, publisher, evidence, notes
  )
  values (
    85,
    'A_GOV_OFFICIAL',
    'opendart_annual_report_2025',
    'STX엔진 2025 OpenDART 사업보고서 직원/재무 현황',
    'https://opendart.fss.or.kr/api/empSttus.json?corp_code=00480455&bsns_year=2025&reprt_code=11011',
    'OpenDART',
    '{"corp_code":"00480455","stock_code":"077970","target_year":"2025","report_code":"11011"}'::jsonb,
    'Generated by scripts/generate-opendart-financials-sql.mjs'
  )
  on conflict (company_id, source_type, source_url) do update
    set title = excluded.title,
        evidence = excluded.evidence,
        notes = excluded.notes,
        retrieved_at = now()
  returning id
)
insert into public.company_financials (
  company_id, fiscal_year, revenue, operating_profit, net_income, employee_count, avg_salary, source_id, notes
)
select
  85, 2025, 789341914687, 69592939476, 68948215486,
  926, 8200, source_upsert.id,
  'OpenDART generated annual-report snapshot'
from source_upsert
where not exists (
  select 1 from public.company_financials existing
  where existing.company_id = 85
    and existing.fiscal_year = 2025
    and existing.notes = 'OpenDART generated annual-report snapshot'
);

insert into public.company_profiles (
  company_id, verified_name, stock_code, dart_corp_code, employee_count, employee_count_year, avg_salary, avg_salary_year, data_quality_score, updated_at
)
values (
  85, 'STX엔진', '077970', '00480455',
  926, 2025, 8200, 2025, 80, now()
)
on conflict (company_id) do update
  set verified_name = coalesce(public.company_profiles.verified_name, excluded.verified_name),
      stock_code = excluded.stock_code,
      dart_corp_code = excluded.dart_corp_code,
      employee_count = excluded.employee_count,
      employee_count_year = excluded.employee_count_year,
      avg_salary = excluded.avg_salary,
      avg_salary_year = excluded.avg_salary_year,
      data_quality_score = greatest(public.company_profiles.data_quality_score, excluded.data_quality_score),
      updated_at = now();

update public.companies
set avg_salary = 8200,
    salary_source = 'OpenDART 2025 사업보고서 직원 현황'
where id = 85
  and 8200 is not null;
-- raw: {"employee":{"employee_count":926,"avg_salary":8200},"financial":{"revenue":789341914687,"operating_profit":69592939476,"net_income":68948215486}}
