import { CompanyProfile, JobPosting } from "@/lib/types";

export const localCompanyProfileEnrichment: CompanyProfile[] = [
  {
    company_id: 35,
    verified_name: "쎄트렉아이",
    homepage_url: "https://www.satreci.com/",
    careers_page_url: "https://satreci.careerlink.kr/",
    main_products: ["위성시스템", "위성영상", "지상체", "항공우주"],
    summary: "위성시스템과 지상체, 위성영상 활용 서비스를 다루는 항공우주 기업입니다.",
    data_quality_score: 76,
  },
  {
    company_id: 64,
    verified_name: "한컴라이프케어",
    homepage_url: "https://www.hancomlifecare.com/",
    careers_page_url: "https://www.hancomlifecare.com/user/bbs/list.do?bbsId=recruitment",
    main_products: ["개인안전장비", "방독면", "소방장비", "국방 안전장비"],
    summary: "소방, 산업, 국방 분야 개인안전장비와 화생방 보호 장비를 제조하는 기업입니다.",
    data_quality_score: 78,
  },
  {
    company_id: 73,
    verified_name: "효성중공업",
    homepage_url: "https://www.hyosungheavyindustries.com/",
    careers_page_url: "https://www.hyosungheavyindustries.com/kr/company/recruitment/personnel-system",
    main_products: ["전력기기", "전동기", "발전기", "함정 전기체계"],
    summary: "전력기기와 중전기 솔루션을 기반으로 함정 전기체계와 산업 인프라 사업을 수행하는 기업입니다.",
    data_quality_score: 72,
  },
];

export const localJobPostingEnrichment: JobPosting[] = [
  {
    id: -6401,
    company_id: 64,
    title: "국방 개발부문 개발자",
    job_function: "국방 장비 연구개발",
    employment_type: "정규직",
    experience_level: "경력",
    preferred_military_experience: "국방사업·장비 개발 경험",
    required_skills: ["기구설계", "HW", "SW", "펌웨어"],
    preferred_skills: ["국방사업 이해", "개인안전장비 개발"],
    location: "경기 용인",
    posting_url: "https://www.hancomlifecare.com/user/bbs/detail.do?bbsId=job&bbsSeq=300&cPage=1",
    is_active: null,
  },
  {
    id: -6402,
    company_id: 64,
    title: "소방영업 경력직",
    job_function: "소방·공공 영업",
    employment_type: "정규직",
    experience_level: "경력",
    preferred_military_experience: "공공기관 대응·장비 운용 경험",
    required_skills: ["공공영업", "채널관리", "제품 소싱"],
    preferred_skills: ["동종업계 경험", "커뮤니케이션"],
    location: "경기 용인",
    posted_at: "2026-04-24",
    deadline_at: "2026-06-25",
    posting_url: "https://www.hancomlifecare.com/user/bbs/detail.do?bbsId=job&bbsSeq=335&cPage=1",
    is_active: false,
  },
  {
    id: -3501,
    company_id: 35,
    title: "쎄트렉아이 채용 홈페이지",
    job_function: "항공우주 SW/HW/품질 직무",
    employment_type: "공고별 확인",
    experience_level: "신입/경력",
    preferred_military_experience: "위성·항공우주·통신전자 운용 경험",
    required_skills: ["임베디드", "위성 관제", "광학", "품질관리"],
    preferred_skills: ["항공우주 도메인 이해"],
    location: "공고별 확인",
    posting_url: "https://satreci.careerlink.kr/",
    is_active: null,
  },
];
